### ISSUE TITLE
Error starting nginx: no such file dhparam.pem

### ISSUE THREAD

**Issue by mikeyz24** [domainaware/parsedmarc#10]
I am following the documentation for installing this and run into an issue.  I'm doing this on a new VM that is running a new install of Debian 9.5 using the minimal install.  Your documentation does not include any instruction on creating the dhparam.pem file.  Not having the file will cause nginx not to start.

I recommend that you add instructions just after creating the self-signed certificate to create the file.  I used the following command to create the file.

`sudo openssl dhparam -out dhparam.pem 4096`

Make sure that the dhparam.pem file is inside the ssl folder.

**Comment by seanthegeek** [comment]
I updated the example NGINX configuration so that dhparams is not needed.
