### ISSUE TITLE
Aggregate report csv only has one unique row per source report email

### ISSUE THREAD

**Issue by quickwick** [domainaware/parsedmarc#104]
The aggregate report .csv appears to only contain one unique row per source report e-mail, and duplicates that row based on the number records in each source report e-mail.

For example, I just parsed 49 report e-mails. parsedmarc generated an aggregate.csv with 392 rows. I used the Excel function Remove Duplicates, and and it deleted 342 rows, leaving 49 unique values.

I undid the duplicate row removal, and looked at the rows for one specific report_id. I opened the matching e-mail report, and looked at the .xml file. The two rows in the aggregate.csv both matched the second record in the .xml file. The first record in the .xml file was not represented in aggregate.csv.

I went back to aggregate.csv reports generated by previous versions of parsedmarc, and this issue was not present. I think this was introduced in 6.5.1.

My current setup:
parsedmarc 6.5.1
Windows 10
Python 3.7.3
Exchange 2013 CU 22
I downloaded that GeoLite2-Country.mmdb and put it in C:\GeoIP\ folder as per instructions

**Comment by seanthegeek** [comment]
This was fixed in 6.5.2, which was just released a few minutes ago.
