### ISSUE TITLE
unable to run as a service.

### ISSUE THREAD

**Issue by CodeNameTheOnlyOne** [domainaware/parsedmarc#108]

**Comment by CodeNameTheOnlyOne** [comment]
i get the following error when i run as a service. need to find out where i need to give it permissons.
WARNING:__init__.py:1014:Message with subject "DMARC Forensic report" is not a valid forensic DMARC report: Unexpected error: Error downloading https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz: [Errno 13] Permission denied: 'GeoLite2-Country_20190806

works fine when i run it from console as root.

**Comment by CodeNameTheOnlyOne** [comment]
changed service to run as root and it is working now. not right but a temp fix.

**Comment by syska** [comment]
Look for the file `GeoLite2-Country.tar.gz` on disk ... it needs access to save that file. As you are running it as root atm ... it should be somewhere ... 

Just an idea ...

**Comment by seanthegeek** [comment]
You need to use run geoipupdate once first before running parsedmarc for the first time. Otherwise, parsedmarc will try to download the database in the current directory, which is why it failed.

This is covered in the installation documentation
https://domainaware.github.io/parsedmarc/#installation

**Comment by CodeNameTheOnlyOne** [comment]
geoip update appears to have been discontinued on centos 7.
this is what i get when i run geoipupdate

geoipupdate
/usr/share/GeoIP/GeoLiteCountry.dat can't be opened, proceeding to download database
Updating /usr/share/GeoIP/GeoLiteCountry.dat
Received Error -21 (Sanity check database_info string failed) when attempting to update GeoIP Database
/usr/share/GeoIP/GeoLiteCity.dat can't be opened, proceeding to download database
Updating /usr/share/GeoIP/GeoLiteCity.dat
Received Error -21 (Sanity check database_info string failed) when attempting to update GeoIP Database


some searching brought me to this.
https://community.nethserver.org/t/geoip-1-x-no-longer-supported/11801/6
any hints?

**Comment by seanthegeek** [comment]
geoipupdate is a python utility I wrote. The OS shouldn't mater. You just need to run it as root at lease once. Do you have SELinux enabled?

**Comment by CodeNameTheOnlyOne** [comment]
im running geoipupdate as insatlled with yum 
does not appear to be python and is provided by maxmind as far as i can tell.
am i needing to install another package?

also tried with se linux off and it did not make a change.
it looks like the program is just not happy with the files it downloads.
geoip v1 vs v2 files as i understand.

**Comment by seanthegeek** [comment]
I'm getting that mixed up with another library I wrote. Sorry.

I guess the geoipupdate package must be outdated in the centos repos?

As a last resort you can download and extract the GeoLite2 Country database manually

https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz

Place the extracted file at /usr/local/share/GeoIP/GeoLite2-Country.mmdb

Make it writeable by your parsedmarc user.
