### ISSUE TITLE
invalid forensic reports

### ISSUE THREAD

**Issue by CodeNameTheOnlyOne** [domainaware/parsedmarc#109]
got a buch of reports that are not getting processed and marked as invaild.
they appear to contain vaid data but im not sure what it does not like.
 i will post some in here.

**Comment by CodeNameTheOnlyOne** [comment]
here is a anonomised copy of the message body

A message claiming to be from you has failed the published DMARC
policy for your domain.

  Sender Domain: mydomain.com
  Sender IP Address: 190.144.119.146
  Received Date: Fri, 16 Aug 2019 15:06:53 +0200
  SPF Alignment: no
  DKIM Alignment: no
  DMARC Results: Quarantine

------ This is a copy of the headers that were received before the error
       was detected.

Received: from [190.144.119.146] (helo=smtp3.delmarvaheart.com)
        by mx41.antispamcloud.com with esmtp (Exim 4.89)
        (envelope-from <cjstipulate@mydomain.com>)
        id 1hybwT-0003Fp-Db
        for temple@isp-thailand.com; Fri, 16 Aug 2019 15:06:53 +0200
From: Merrili T. <cjstipulate@mydomain.com>
To: Temple <temple@isp-thailand.com>
Subject: My boobs and pussy waiting for you
Date: Fri, 16 Aug 2019 08:07:21 -0500
MIME-Version: 1.0
Content-Type: multipart/alternative;
        boundary="----=_NextPart_000_003B_01D50A68.7F8707D0"
X-Priority: 3
X-MSMail-Priority: Normal
Importance: Normal
X-Mailer: Microsoft Windows Live Mail 16.4.3528.331
X-MimeOLE: Produced By Microsoft MimeOLE V16.4.3528.331
X-EsetId: 37303A298B00076A667D64
X-EsetScannerBuild: 41387
Received-SPF: fail (mx41.antispamcloud.com: domain of mydomain.com does not designate 190.144.119.146 as permitted sender) client-ip=190.144.119.146; envelope-from=cjstipulate@mydomain.com; helo=smtp3.delmarvaheart.com;
X-SPF-Result: mx41.antispamcloud.com: domain of mydomain.com does not designate 190.144.119.146 as permitted sender
X-Sender-Warning: Reverse DNS lookup failed for 190.144.119.146 (failed)
X-DKIM-Status: none /  / mydomain.com /  /  /

**Comment by CodeNameTheOnlyOne** [comment]
not sure if these messages dont comply with a standard or if the format just needs to be added.
when i set my policy to enforcing i got a bunch of these.

**Comment by seanthegeek** [comment]
That's not a valid format. For some reason some reporting servers like to come up with their own formats, unfortunately.
