### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by gmalsack** [domainaware/parsedmarc#114]
Your instructions are as follows:

On CentOS systems, run:

sudo yum install -y python34-setuptools GeoIP-Update
sudo easy_install-3.4 pip
sudo geoipupdate

On CentOS 6.10:
1, GeoIP-Update doesn't exist, if you install the epel-release repository, the correct package name is geoipupdate
2, You must also have python34-devel in order to run the installation script, otherwise it crashes while trying to compile

**Comment by seanthegeek** [comment]
Fixed. Thanks!
