### ISSUE TITLE
spf_result field missing from csv file

### ISSUE THREAD

**Issue by mbchandler** [domainaware/parsedmarc#115]
Sometimes the spf_result is missing as the last field and all I see at the end of the line is "mfrom,". The result is included in the xml file:

<auth_results>
      <spf>
        <domain>example.com</domain>
        <scope>mfrom</scope>
        <result>pass</result>
      </spf>
    </auth_results>

Other times, the spf_result is there, "mfrom,pass". I can't see a pattern in regards to sending org, domain, etc.. I'm using version 6.5.4.

**Comment by seanthegeek** [comment]
Fixed in 6.7.0 release.

Replaced `spf_result` and `dkim_result` CSV feild with `spf_aligned`, `dkim_aligned`, and `dmarc_aligned` boolean  fields.
