### ISSUE TITLE
Shared mailbox on EWS issue

### ISSUE THREAD

**Issue by Ans3L** [domainaware/parsedmarc#116]
Hi!
Love your work, it's incredibly comprehensive and useful.
I had some difficulties in configuring the monitoring of a shared mailbox on EWS and I thought it could be useful for others to share my workaround.

First of all, I needed to install and configure DavMail (as described by the manual), but then to access a shared mailbox, the reports_folder parameter in the config file must look like this:
`reports_folder = /users/sharedbox@domain.com/...`
Anyway, when I run paresedmarc, I get an imap "select" error, because the python library "mailsuite" that you use as imap client automatically strips away the first "/".

My dirty workaround was to comment out line 40 in mailsuite/imap.py, that is 
`#folder_name = folder_name.strip("/")`

Would be awsome if you could suggest a better (update resistent) solution or use a different imap client which allows folders starting with a slash.

**Comment by seanthegeek** [comment]
Thanks for the bug report. I also wrote the `mailsuite` library. I just pushed a fix that will only strip trailing slashes from folder paths, not leading slashes. Can you try installing this version by running:

```bash
sudo -H pip install -U git+https://github.com/seanthegeek/mailsuite
```

If that works for you, i'll release a new version of `mailsuite` and create a new release of `parsedmarc` that uses it

**Comment by Ans3L** [comment]
Great thanks!
But I think there is still a similar issue when paresedmarc finds an invalid report and mailsuite tries to move the email to the invalid folder. It's in line 307 of imap.py, the final strip should probably be rstrip as well.

**Comment by seanthegeek** [comment]
Fixed. Let me know how this works and I'll release it.

**Comment by Ans3L** [comment]
Everything seems to be working fine.
Thanks a lot!
