### ISSUE TITLE
Forensic DMARC data not displaying information

### ISSUE THREAD

**Issue by gmalsack** [domainaware/parsedmarc#117]
Hi Sean,

I downloaded the xml files and created the dashboards. I let my system run for several days. The email address I have configured in my txt records shows that I have numerous aggregate reports that have been process and have been moved from INBOX to Archive/Aggregate. When I open the Aggregate report, I see a ton of helpful data.

However, when I look at Archive/Forensic there are a couple of emails there, 4 to be exact. When I go to the Forensic dashboard though it says no data found or something to that extent.

So I created a clone of the dashboard and began hacking away at it. What I may have found to be the issue is the syntax at which the fields are referred to. I rebuilt the queries using the query builder in the front search form of Splunk. Now, I don't know if the query syntax is different from various versions, but I'm running Splunk Enterprise Version: 7.3.2.

Anyway, I finally got it to work, so I thought I would send an updated version of the XML that I'm using in case others run into the same issue.

Thanks for the original work!!!
Greg
[Splunk Forensic Update.txt](https://github.com/domainaware/parsedmarc/files/3742249/Splunk.Forensic.Update.txt)

**Comment by fraserc182** [comment]
Just chiming in here to say thank you for sorting this! 
I just accepted I wasn't getting any forensic information, but with your new dashboard source I can see info.

Thanks!

**Comment by seanthegeek** [comment]
I committed your fix. Thanks!
