### ISSUE TITLE
Not a valid aggregate DMARC report

### ISSUE THREAD

**Issue by dinigalab** [domainaware/parsedmarc#123]
Hi,

I have just installed Parsedmarc and I am errors messages. (see attachment)
Parsedmarc is able to connect to my inbox and archive received messages in the invalid archive.

Thanks for your help.
[parsedmarc_issue.txt](https://github.com/domainaware/parsedmarc/files/3825047/parsedmarc_issue.txt)

**Comment by seanthegeek** [comment]
Hi,

You need to install the Maxmind GeoIP database first

On Debian or Ubuntu systems, run:

sudo apt-get install -y python3-pip geoipupdate
sudo geoipupdate

On CentOS systems, run:

sudo yum install -y python34-setuptools python34-devel geoipupdate
sudo easy_install-3.4 pip
sudo geoipupdate

**Comment by dinigalab** [comment]
Thanks
It is working now.
What is the frequency that Parsedmarc need to update the Maxmind GeoIP Database?

**Comment by seanthegeek** [comment]
Not very often at all, since we are only doing geolocation at the country level. Maybe once every six months if you want to make sure the country identification is accurate.
