### ISSUE TITLE
Update Grafana dashboard

### ISSUE THREAD

**Issue by bhozar** [domainaware/parsedmarc#127]
I've updated the dashboard and put it in a repo: https://github.com/bhozar/grafana-dashboards/tree/master/parsedmarc

Now includes ability to filter on "From Domain" as well as tidied up a load of other stuff.

I've also included it on Grafana.com: https://grafana.com/grafana/dashboards/11227

**Comment by seanthegeek** [comment]
Thanks. I just submitted a PR for your dashboard.

Update the titles of the over time graphs to match the Elasticsearch field names and pie chart names.

Those fields don't track if SPF or DKIM pass on their own. The domains used for the SPF/DKIM check that pass must **also** match/align with the message from header domain.

If you could update your dashboard and screenshots on github.com and and graphana.com, that would be awesome.

**Comment by bhozar** [comment]
Thanks, have merged your changes.

So am I reading it right that I need to make more changes?

**Comment by seanthegeek** [comment]
Just update the screenshots, in your repo and update the dashboard download and screenshots at graphana.com :)

**Comment by bhozar** [comment]
All updated on Grafana.com and my repo. Thanks.
