### ISSUE TITLE
spf_result softfail missing

### ISSUE THREAD

**Issue by kokosun** [domainaware/parsedmarc#128]
Hello,

And thanks for this work.
For your information, the spf_result [SOFTFAIL] is always missing.
I have : pass/none/fail but never the softfail.

I saw this line in the spf_result part of the __init__.py file:

            **row["spf_results"] = ",".join(map(to_str, dkim_results))**

_spf_results = []
            for spf_result in record["auth_results"]["spf"]:
                spf_domains.append(spf_result["domain"])
                spf_scopes.append(spf_result["scope"])
                spf_results.append(spf_result["result"])
            row["spf_domains"] = ",".join(map(to_str, spf_domains))
            row["spf_scopes"] = ",".join(map(to_str, spf_scopes))
            row["spf_results"] = ",".join(map(to_str, dkim_results))_

It could be the problem ?

Regards

kokosun

**Comment by seanthegeek** [comment]
Fixed in parsedmarc 6.7.2
