### ISSUE TITLE
Kibana import error

### ISSUE THREAD

**Issue by Vico999** [domainaware/parsedmarc#130]
Kibana v7.5 with ElasticSearch v7.5
When I tried to import `kibana_saved_objects.json` I received this error:
```
Import failed
Failed to import 2 of 22 objects. Import failed
this.patternCache.clear is not a function this.patternCache.clear is not a function
```
It also had a recommended note:
```
Support for JSON files is going away
Use our updated export to generate NDJSON files, and you'll be all set.
```

**Comment by seanthegeek** [comment]
I created a NDJSON file, but forgot to update the documentation. Sorry about that. You can find it at

https://raw.githubusercontent.com/domainaware/parsedmarc/master/kibana/export.ndjson

**Comment by seanthegeek** [comment]
I just fixed the documentation.
