### ISSUE TITLE
Add OAuth support for IMAP on GSuite

### ISSUE THREAD

**Issue by kguest** [domainaware/parsedmarc#131]
Not sure if this needs to be a feature request but Google have just announced they are deprecating support for static passwords:

https://docs.google.com/document/d/1BECVqUiapTmAbycQpG_WfkIvYd0OAL58pPmq7q96kQ4

https://developers.google.com/gmail/imap/xoauth2-protocol

**Comment by seanthegeek** [comment]
This is a duplicate of issue #96, but now that IMAP Gmail (and Office 365) have deprecated IMAP, I need to prioritize this. Not exactly sure when I'll get to it, as this is a personal side project, but I need to get it done before they cut off IMAP.
