### ISSUE TITLE
urllib version conflict

### ISSUE THREAD

**Issue by lukecyca** [domainaware/parsedmarc#134]
When installing I get:
```
 ERROR: geoip2 3.0.0 has requirement urllib3>=1.25.2, 
 but you'll have urllib3 1.24.3 which is incompatible.
```

This is because the `geoip2>=2.9.0` requirement is now pulling geoip2 3.0.0 which requires `urllib3>=1.25.2`. But this package requires `urllib3<1.25,>=1.21.1` which is a conflict.

### Proposed solution

Set this package to require `geoip2==2.9.0` exactly.

**Comment by seanthegeek** [comment]
Fixed in 6.7.4 by updating add related dependencies.
