### ISSUE TITLE
% in IMAP password creates an error

### ISSUE THREAD

**Issue by MatthK** [domainaware/parsedmarc#136]
I just setup parsedmarc and had troubles to get it up and running. Eventually I figured out that a % character in the password of the email account created some exceptions and made parsedmarc fail to start.

**Comment by Kuzuto** [comment]
I just testet this. If you put an extra % in the config file for the password, it works.
Two %% will be converted to One % when python reads the code.

**Comment by MatthK** [comment]
Thanks. I adjusted the password and used one without a %, but possibly it will help somebody else in the future.
