### ISSUE TITLE
MaxMind registration and licensing changes

### ISSUE THREAD

**Issue by JamesWhyley** [domainaware/parsedmarc#137]
Hello,

Firstly, I very much enjoy ParseDMARC, it's an excellent little tool. 

Secondly, as I'm sure people may have noticed, MaxMind changed their licensing arrangements on December 30th to require registration as per https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/ and this now causes ParseDMARC to error if you're not running it offline. 

Observed behaviour, using the free DB offering, is that it does the usual call to the old GeoLite2 download location, finds nothing, retries, throws an error, then moves on to the next message. It would appear that nothing subsequently appears in elasticsearch either.

Log looks llike this `   DEBUG:__init__.py:1074:Processing message 1 of 314: UID 74051
   ERROR:utils.py:331:Error downloading https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz: HTTPSConnectionPool(host='geolite.maxmind.com', port=443): Max retries exceeded with url: /download/geoip/database/GeoLite2-Country.tar.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd10518df10>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

Processing offline works as usual.

Edit: Sorry, I should have said it works perfectly fine if you have a pre-existing GeoLite2 db as well.

**Comment by robertitox** [comment]
Dear, I have a Debian 10 box with parsedmarc and I know yoy said. I've downloaded the GeoLite2-Country.mmdb and put it in /usr/share/GeoIP. After that I ran "parsedmarc -c /etc/parsedmarc.ini" and the error you mentioned has disappeared.

But my problem is that I can see the Map of Message source countries at all on Kibana, please can anybody tell me how to see the map locations ?

I've just setup "chown -R root.parsedmarc /usr/share/GeoIP" and "chmod -R 664 /usr/share/GeoIP".

Nw inside /usr/share/GeoIP I have these files:

GeoIPASNum.dat  
GeoIPCity.dat  
GeoIP.dat  
GeoIPv6.dat  
GeoLite2-Country.mmdb

Thanks a lot !

**Comment by dragoangel** [comment]
Need ad some API keys to config and use new links to download GeoIP

**Comment by seanthegeek** [comment]
@robertitox What do you mean? The map and source data should always be included in the dashboard.

**Comment by seanthegeek** [comment]
Hi all. 

MaxMind now requires users to register for a free account in order to download their GeoLite2 databases. Instead of reinventing the wheel, I decided to provide documentation on how to use MaxMind's `geoipupdate` tool, rather than trying to build that function into `parsedmarc`.

https://domainaware.github.io/parsedmarc/#geoipupdate-setup

I just released `parsedmarc` 6.8.0, which removes the code that tries to download the MaxMind database.

After setting up `geoipupdate`, you can upgrade `parsedmarc` by running

```bash
sudo -H pip install -U parsedmarc
```

Let me know if you have any questions.

**Comment by JamesWhyley** [comment]
Makes sense to me, nice one. Cheers.
