### ISSUE TITLE
Can't see Reverse DNS information

### ISSUE THREAD

**Issue by robertitox** [domainaware/parsedmarc#138]
Dear, after implementation of parsedmarc/elasticsearch/kibana, I can't see on Kibana dashboard the Reverse DNS fields, they are empty (I attach a print screen below). I don't know if it's a parsedmarc problem or maybe some other issue.

In my Debian box I have setup my own public DNS's, and not DNS's from Internet. My own public DNS's can make reverse resolution as I could verify.

Thanks a lot.

![reversedns](https://user-images.githubusercontent.com/47980031/72076405-3c0a8780-32d4-11ea-968c-bb29fa2550b4.JPG)

**Comment by seanthegeek** [comment]
By default, parsedmarc queries Cloudflare's public DNS resolvers. It is possible that your network only allows DNS queries your local DNS resolvers.

Try setting the `nameservers` option in the `[general]` section of `parsedmarc.ini` to your local DNS servers, separated by commas.
