### ISSUE TITLE
install on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Rimers** [domainaware/parsedmarc#142]
When trying to install on Ubuntu 18.04.03 LTS using PIP i get following issue.
 pip install mail-parser --no-cache-dir
Collecting mail-parser
  Downloading https://files.pythonhosted.org/packages/21/8d/50ce414921deb761cf29e148cfe606587cdb041ede06c06390600e467496/mail-parser-3.12.0.tar.gz
Collecting ipaddress==1.0.23 (from mail-parser)
  Downloading https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl
Collecting simplejson==3.17.0 (from mail-parser)
  Downloading https://files.pythonhosted.org/packages/98/87/a7b98aa9256c8843f92878966dc3d8d914c14aad97e2c5ce4798d5743e07/simplejson-3.17.0.tar.gz (83kB)
    100% |████████████████████████████████| 92kB 8.2MB/s
Collecting six==1.14.0 (from mail-parser)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Installing collected packages: ipaddress, simplejson, six, mail-parser
  Running setup.py install for simplejson ... done
  Running setup.py install for mail-parser ... done
Successfully installed ipaddress-1.0.23 mail-parser-3.12.0 simplejson-3.17.0 six-1.14.0
nils@ubuntu-parsedmarc:~$ pip install parsedmarc --no-cache-dir
Collecting parsedmarc
  Downloading https://files.pythonhosted.org/packages/33/6f/f7b8e73557b66835f5e91096e92f8d5d55bb790eead2205c00fd638a314e/parsedmarc-6.8.2.tar.gz (41kB)
    100% |████████████████████████████████| 51kB 8.9MB/s
Collecting dateparser>=0.7.2 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/82/9d/51126ac615bbc4418478d725a5fa1a0f112059f6f111e4b48cfbe17ef9d0/dateparser-0.7.2-py2.py3-none-any.whl (352kB)
    100% |████████████████████████████████| 358kB 17.3MB/s
Collecting dnspython>=1.16.0 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 194kB 24.2MB/s
Collecting elasticsearch-dsl<7.0.0,>=6.3.1 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/4f/73/580e648ab72a19c26c815931ce2b2dda67454f557e72ce7ae90fd3b7887d/elasticsearch_dsl-6.4.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 66.8MB/s
Collecting elasticsearch<7.0.0,>=6.3.1 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/e0/b3/14dd62dfee3b0bca512167edc6f8baf5149b1108a02f9f246021953d117c/elasticsearch-6.4.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 64.6MB/s
Collecting expiringdict>=1.1.4 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/46/dc/76035d63cbed1ed10db311bb027649b9b73315d7bff7ad03abda637fa23f/expiringdict-1.2.0.tar.gz
Collecting geoip2>=3.0.0 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/b6/18/228c84599dbc28bc7b3343e9eeaf675193f9bfa4de217d4ebf126c24dce3/geoip2-3.0.0-py2.py3-none-any.whl
Collecting imapclient>=2.1.0 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/dc/39/e1c2c2c6e2356ab6ea81fcfc0a74b044b311d6a91a45300811d9a6077ef7/IMAPClient-2.1.0-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 63.4MB/s
Collecting kafka-python>=1.4.4 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/49/c9/9863483a1353700ba87821b4f39085eb18fd1bcbb1e954c697177d67f03f/kafka_python-1.4.7-py2.py3-none-any.whl (266kB)
    100% |████████████████████████████████| 266kB 45.8MB/s
Collecting lxml>=4.4.0 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/03/06/eb9f000882f671a2d494342c1fe93b1c8b18fb04420bb611aeaa3298ef17/lxml-4.5.0-cp27-cp27mu-manylinux1_x86_64.whl (5.7MB)
    100% |████████████████████████████████| 5.7MB 16.7MB/s
Collecting mail-parser>=3.11.0 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/21/8d/50ce414921deb761cf29e148cfe606587cdb041ede06c06390600e467496/mail-parser-3.12.0.tar.gz
Collecting mailsuite>=1.5.4 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/1f/3f/3dce6befed2ec1121cf1dd2eb88bbe59a3269df510bebb42e860d0fb8f67/mailsuite-1.5.4.tar.gz
Collecting publicsuffix2>=2.20190812 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/9d/16/053c2945c5e3aebeefb4ccd5c5e7639e38bc30ad1bdc7ce86c6d01707726/publicsuffix2-2.20191221-py2.py3-none-any.whl (89kB)
    100% |████████████████████████████████| 92kB 60.9MB/s
Collecting requests>=2.22.0 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 72.4MB/s
Collecting tqdm>=4.31.1 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/cc/2e/4307206db63f05ed37e21d4c0d843d0fbcacd62479f8ce99ba0f2c0875e0/tqdm-4.42.0-py2.py3-none-any.whl (59kB)
    100% |████████████████████████████████| 61kB 69.3MB/s
Collecting urllib3>=1.25.7 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 73.7MB/s
Collecting xmltodict>=0.12.0 (from parsedmarc)
  Downloading https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Collecting pytz (from dateparser>=0.7.2->parsedmarc)
  Downloading https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl (509kB)
    100% |████████████████████████████████| 512kB 17.9MB/s
Collecting tzlocal (from dateparser>=0.7.2->parsedmarc)
  Downloading https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl
Collecting python-dateutil (from dateparser>=0.7.2->parsedmarc)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 32.0MB/s
Collecting regex (from dateparser>=0.7.2->parsedmarc)
  Downloading https://files.pythonhosted.org/packages/73/d9/b58289d885180b5d538aa6df07974b5fe6088547ac846c0f76f77259c304/regex-2020.1.8.tar.gz (681kB)
    100% |████████████████████████████████| 686kB 16.9MB/s
Collecting six (from elasticsearch-dsl<7.0.0,>=6.3.1->parsedmarc)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3.3" (from elasticsearch-dsl<7.0.0,>=6.3.1->parsedmarc)
  Downloading https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl
Collecting typing (from expiringdict>=1.1.4->parsedmarc)
  Downloading https://files.pythonhosted.org/packages/22/30/64ca29543375759dc589ade14a6cd36382abf2bec17d67de8481bc9814d7/typing-3.7.4.1-py2-none-any.whl
Collecting maxminddb>=1.5.2 (from geoip2>=3.0.0->parsedmarc)
  Downloading https://files.pythonhosted.org/packages/f0/a8/4a12f15f145b1d37851a511ec0093221c057f59809cf891cd1be99de0e24/maxminddb-1.5.2.tar.gz (274kB)
    100% |████████████████████████████████| 276kB 15.6MB/s
Collecting simplejson==3.17.0 (from mail-parser>=3.11.0->parsedmarc)
  Downloading https://files.pythonhosted.org/packages/98/87/a7b98aa9256c8843f92878966dc3d8d914c14aad97e2c5ce4798d5743e07/simplejson-3.17.0.tar.gz (83kB)
    100% |████████████████████████████████| 92kB 58.5MB/s
Collecting html2text>=2020.1.16 (from mailsuite>=1.5.4->parsedmarc)
  Could not find a version that satisfies the requirement html2text>=2020.1.16 (from mailsuite>=1.5.4->parsedmarc) (from versions: 2.35, 2.37, 2.38, 3.1, 3.2, 3.101, 3.200.0, 3.200.1, 3.200.2, 3.200.3, 2014.4.5, 2014.7.3, 2014.9.7, 2014.9.8, 2014.9.25, 2014.12.5, 2014.12.24, 2014.12.29, 2015.2.18, 2015.4.13, 2015.4.14, 2015.6.6, 2015.6.12, 2015.6.21, 2015.11.4, 2016.1.8, 2016.4.2, 2016.5.29, 2016.9.19, 2017.10.4, 2018.1.9, 2019.8.11)
No matching distribution found for html2text>=2020.1.16 (from mailsuite>=1.5.4->parsedmarc)

**Comment by seanthegeek** [comment]
I cannot reproduce this error. html2text 2020.1.16 is the latest release.

https://pypi.org/project/html2text/#history

Please ensure your HTTP proxies are not caching out-of-date information.
