### ISSUE TITLE
Emails marked as non-compliant, but data suggest otherwise

### ISSUE THREAD

**Issue by dankorsholm** [domainaware/parsedmarc#153]
Hi,

Multiple emails are returned as false in spf_aligned and dkim_aligned, therefore failing passed_dmarc.
But data in the rapport says:
spf_result:
{
  "domain": "sendgrid.net",
  "scope": "mfrom",
  "result": "pass"
}
dkim_result:
{   
  "domain": "sendgrid.net",   
  "selector": "smtpapi", 
  "result": "pass" 
}

Why is the aligned values then false when it says pass in the result?

Best regards
Dan

**Comment by Kuzuto** [comment]
Can you post the full xml report ?
Or what is the values of "header_from", "passed_dmarc" ?

**Comment by dankorsholm** [comment]
This is the JSON data from Kibana:
{
  "_index": "dmarc_aggregate-2020-03",
  "_type": "doc",
  "_id": "n38VznABEL__2rGtkDis",
  "_version": 1,
  "_score": null,
  "_source": {
    "xml_schema": "draft",
    "org_name": "google.com",
    "org_email": "noreply-dmarc-support@google.com",
    "org_extra_contact_info": "https://support.google.com/a/answer/2466580",
    "report_id": "6258752542545724988",
    "date_range": [
      "2020-03-11T00:00:00",
      "2020-03-11T23:59:59"
    ],
    "published_policy": {
      "domain": "tivoli.dk",
      "adkim": "r",
      "aspf": "r",
      "p": "none",
      "sp": "none",
      "pct": 100,
      "fo": "0"
    },
    "source_ip_address": "198.37.150.166",
    "source_country": "US",
    "source_reverse_dns": "csnrwsxs.outbound-mail.sendgrid.net",
    "source_base_domain": "sendgrid.net",
    "message_count": 988,
    "disposition": "none",
    "dkim_aligned": false,
    "spf_aligned": false,
    "header_from": "tivoli.dk",
    "envelope_from": "sendgrid.net",
    "dkim_results": [
      {
        "domain": "sendgrid.net",
        "selector": "smtpapi",
        "result": "pass"
      }
    ],
    "spf_results": [
      {
        "domain": "sendgrid.net",
        "scope": "mfrom",
        "result": "pass"
      }
    ],
    "passed_dmarc": false
  },
  "fields": {
    "date_range": [
      "2020-03-11T00:00:00.000Z",
      "2020-03-11T23:59:59.000Z"
    ]
  },
  "sort": [
    1583971199000
  ]
}

Ill look for the XML report

**Comment by dankorsholm** [comment]
I see they say failed on alignment when i check through mxtoolbox. Ill probably just have to read up a bit more on what these values mean :)
Thanks anyway

**Comment by Kuzuto** [comment]
Hej.. ser ud til vi kan tage den på dansk, men gør det på engelsk.

The emails are send from Sendgrid, with spf and dkim. But the header is tivoli.dk
"header_from": "tivoli.dk"
So the email is not Aligned with DMARC, as you need to have either the SPF from to be tivoli.dk or the DKIM signing to be tivoli.dk.
It's not possible to get Sendgrid to send with tivoli.dk as the SPF (envelope-from) so you need to activate the DKIM signing (Domain Authentication) to get them to sign with your domain.
Here is how to do that : https://sendgrid.com/docs/ui/account-and-settings/how-to-set-up-domain-authentication/
If you need help with this, send me a private message. I'm doing DMARC implementations as a service, and helped many companies to be DMARC compliant.

**Comment by dankorsholm** [comment]
Hej, ah en dansker, rart :)

Yeah lets do it in english. I see what youre saying, but they are already allowed through our SPF, wouldnt they then be true on SPF alligned?
Sendgrid already have txt records on our DNS, so i would assume DKIM also should be fine.

I do think i need to read up on this.

Im not really able to find the private message part.
Also we are very heavily affected by the Coronavirus.

**Comment by Kuzuto** [comment]
DMARC is validating the Envelope-From (SPF) & DKIM d= domain, with the Header-From value on the email.
If both the SPF and the DKIM domain is not the same as the Header-From, then it's not Compliant.
When you have a DMARC record, it's important to have either the Envelope-From (Sending domain, that is getting validated with SPF) or the DKIM signing domain (d= value in the header of the email) to be the same as the Header-From value in the email.

Sendgrid is using their own domain as the  Envelope-From (@sendgrid.net) with a random email address to track if the receiver is getting the email.
So it's not possible to get the SPF part aligned with DMARC.
You have to activate the Domain Authentication in Sendgrid to get them to Sign your emails with your domain. The d= in the header, will then me the same as the Header-From, and the DMARC will be aligned.
This is a normal procedure with DMARC implementation for all 3-party mass-mail services.
