### ISSUE TITLE
IMAP Error: LIST failed: Folder not found

### ISSUE THREAD

**Issue by joker32** [domainaware/parsedmarc#154]
Environment:
Parsedmarc 6.9.0
Ubuntu 18.04
Davmail -> Exchange Online

On mailbox access, Parsedmarc crashes. Accessing the mailbox via IMAP using telnet or Thunderbird works on the Ubuntu system.

Mar 22 10:27:27 exomgmtsrv01 systemd[1]: parsedmarc.service: Failed with result 'exit-code'.
Mar 22 10:27:27 exomgmtsrv01 systemd[1]: parsedmarc.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 10:27:27 exomgmtsrv01 parsedmarc[107618]:    ERROR:cli.py:605:IMAP Error: LIST failed: Folder not found
Mar 22 10:27:27 exomgmtsrv01 parsedmarc[107618]: [38B blob data]
Mar 22 10:27:25 exomgmtsrv01 systemd[1]: Started parsedmarc mailbox watcher.
Mar 22 10:27:25 exomgmtsrv01 systemd[1]: Stopped parsedmarc mailbox watcher.

[general]
save_aggregate = True
save_forensic = True
log_file = /var/log/parsedmarc/parsedmarc.log
debug = True

[imap]
host = 127.0.0.1
port = 1143
ssl = False
watch = True
user = user@domain.tld
password = xxxxx

[elasticsearch]
hosts = 127.0.0.1:9200
ssl = False

**Comment by ninux51** [comment]
Hello,
I had the same issue
Parsedmarc 6.9.0
Debian 10
Davmail -> Exchange Online

Mar 27 16:46:44 xxxx systemd[1]: Started parsedmarc mailbox watcher.
Mar 27 16:46:48 xxxx parsedmarc[2162]: #0150it [00:00, ?it/s]#0150it [00:00, ?it/s]
Mar 27 16:46:48 xxxx parsedmarc[2162]:    ERROR:cli.py:605:IMAP Error: LIST failed: Folder not found
Mar 27 16:46:48 xxxx systemd[1]: parsedmarc.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 16:46:48 xxxx systemd[1]: parsedmarc.service: Failed with result 'exit-code'.
Mar 27 16:49:53 xxxx systemd[1]: Stopped parsedmarc mailbox watcher.
Mar 27 16:50:03 xxxx systemd[1]: Started parsedmarc mailbox watcher.

Works also with telnet on Davmail with no error

**Comment by ninux51** [comment]
Find the solution you shou:d create 3 folders on Exchange Online
Archive/Aggregate
Archive/Forensic
Archve/Invalid

Now it works :)

**Comment by joker32** [comment]
Great, thanks for the tip, now it works.
Thanks!
