### ISSUE TITLE
Index prefix instead of suffix

### ISSUE THREAD

**Issue by wsandin** [domainaware/parsedmarc#159]
I'm currently using parsedmarc and find it be a fantastic solution for dmarc reporting whilst still relying on open-source software.

However I, and many others I believe have an ElasticSearch index layout where I'd put my application name as a prefix rather than a suffix. 

Would it be possible to add a feature to name the index with a prefix?

I'd be happy to draft a pull request if you agree that it's a desirable feature.

**Comment by PauluzzNL** [comment]
@wsandin Just replying as a third-party but I think this feature is always a nice addition so I don't see any reason not to make a PR. There's no drawback having this integrated.

**Comment by Gradlon** [comment]
Is there a plan to implement this feature, request?
We rely on prefixes to grant permissions to our customers.
