### ISSUE TITLE
Failed to import export.ndjson with kibana 6.7.1

### ISSUE THREAD

**Issue by jisnardo** [domainaware/parsedmarc#171]
Failed to import export.ndjson with kibana 6.7.1

Sorry, there was an error
The file could not be processed.

[root@host venvs]# parsedmarc -v
6.10.0

https://domainaware.github.io/parsedmarc/index.html?highlight=ndjson#upgrading-kibana-index-patterns

Any suggestion will be great.

Thanks.

**Comment by Josep-Oliver** [comment]
Hello,

I have the same problem as Jorge, I cannot import the export.ndjson in kibana.

Also I try to remove the part of the code to create an index pattern for the Forensic dashboard but it doesn't allow me either.

Could you help me

a greeting

**Comment by danihodovic** [comment]
Same in v7.8.0

**Comment by osgpcq** [comment]
I was able in Kibana v7.7.0 some month ago.
Now I'm not able to import it in Kibana v6.8.8.

**Comment by osgpcq** [comment]
Maybe related to ?
https://discuss.elastic.co/t/saved-items-import-export-json-ndjson-discrepancy/199834/3
"I checked with our dev team and they said we don't support downgrade patterns, only upgrade."

**Comment by nhairs-finder** [comment]
I believe this is the same problem as https://github.com/domainaware/parsedmarc/issues/141, a work around is to download an older version of `export.ndjson`

**Comment by osgpcq** [comment]
> I believe this is the same problem as #141, a work around is to download an older version of `export.ndjson`

Well I tried both solutions proposed to import in 6.8.8 without success.
Have you other versions of the file I could try?
(Maybe kibana version - import file version could be documented ?). 
Kibana 7.4.0 -- Import file version (e054bc7)  ?
...

**Comment by jisnardo** [comment]
Upgrade or download an older version, that's it.+

Thanks.

**Comment by vikasatverma** [comment]
Here I'm running Kibana 7.9.2 but still unable to import the saved objects
