### ISSUE TITLE
skip_certificate_verification for elastic hosts

### ISSUE THREAD

**Issue by mans39** [domainaware/parsedmarc#174]
Hello,

It's possible to implement skip_certificate_verification for elastic hosts ?

Because my elastic cluster works only with SSL/TLS but with an auto-signed cert.

I trie to set skip_certificate_verification = True but it doesn't work :

WARNING:base.py:212:HEAD https://1******:9200/dmarc_aggregate [status:403 request:0.024s]
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, '')

Regards,

**Comment by strompa** [comment]
I also vote for that this option is implemented. (if it not already does)

**Comment by seanthegeek** [comment]
@mans39  That error isn't related to a certificate verification. A HTTP 403 Forbidden error means your Elasticsearch server has denied access to the client.

**Comment by mans39** [comment]
Hi,

Indeed, Http 403 is relatee to a lack of authorization but in my case, I have correctly specify a login/password but as I used a self signed certificate, this one can't be validate and login process failed.

Regards
