### ISSUE TITLE
Sending reports from Office 365

### ISSUE THREAD

**Issue by J-Henry81** [domainaware/parsedmarc#187]
I am trying to configure ParseDMARC to pull reports from Office 365 but I think I am missing something, how does ParseDMARC know which account to use?

Other than this line # base Exchange OWA or EWS url
davmail.url=https://outlook.office365.com/EWS/Exchange.asmx
I haven't seen any other information about accounts, like I said I think I am just over looking something but any pointers wopuld be helpful.

**Comment by bhozar** [comment]
I set it up as an IMAP account in 365.

[imap]
host = outlook.office365.com
user = account@example.com
password = Strong_Password
watch = True
#test = True
timeout = 120

**Comment by Raithmir** [comment]
You just need to point parsedmarc.ini to your davmail instance and specify the logon details...

[imap]
host = 127.0.0.1
port=1143
ssl=False
user = dmarc@<your tennant>.onmicrosoft.com
password = ThisIsAPassword
reports_folder = INBOX
archive_folder = Archive
watch = True
