### ISSUE TITLE
ERROR:cli.py:605:IMAP Error: open() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by mueller-dv** [domainaware/parsedmarc#189]
When i start parsedmarc, i get the following message:

ERROR:cli.py:605:IMAP Error: open() takes 3 positional arguments but 4 were given

My ini looks like:

[general]
save_aggregate = True
save_forensic = True
output = /output/

[imap]
test = True
host = mail.de.server.com
user = dmarc@de.server.com
password = xxxxxxxxxxxxxxxxxxxxxx
watch = True

[smtp]
host = mail.de.server.com
user = dmarc@de.server.com
password = xxxxxxxxxxxxxxxxxxxxxx
from = dmarc@de.server.com
to = admin@de.server.com

[elasticsearch]
hosts = elasticsearch:9200
ssl = False

**Comment by Keramblock** [comment]
same

**Comment by Keramblock** [comment]
After I changed python 3.9(python:latest) to 3.8 - problem was fixed for me. So probably issue is assosiated with new python.

**Comment by Keramblock** [comment]
@seanthegeek FYI

**Comment by MarcelWaldvogel** [comment]
The latest released [`IMAPClient` version is 2.1.0 from 2020-07-19, which claims it only officially supports Python up to 3.7](https://imapclient.readthedocs.io/en/2.1.0/). However, [3 months ago, test cases for Python 3.8 and 3.9 were added](https://github.com/mjs/imapclient/commit/9f7f64d691641a0fc10c3c7856ca9cb8b0a90b7f). Maybe some incompatibilities were fixed around there as well.

If there is a need to touch the IMAP code in ParseDMARC, it would be great to add support for `STARTTLS` (there are mail servers out there not supporting the legacy SSL interface anymore).

**Comment by bhulsken** [comment]
Updating to IMAPClient 2.2.0 (released last month) fixed this error for me. I was getting it using 2.1.0, so I think this issue can be closed.

**Comment by wieczorek1990** [comment]
Still affected.
