### ISSUE TITLE
Cannot retreive reports from mailbox

### ISSUE THREAD

**Issue by thekman37** [domainaware/parsedmarc#195]
I'm receiving 2 different errors when trying to check a mailbox for DMARC reports.
The DMARC reports sit in a folder beneath the Inbox called DMARCReports.
Davmail is running on the same machine connecting to a Exchange 2019 EWS.
Parsedmarc is then connecting to Davmail on port 1143.

The error I receive is:

ERROR:cli.py:605:IMAP Error: LIST failed: Folder not found

Or by adjusting the folder names I receive the following:

ERROR:cli.py:605:IMAP Error: select failed: Not found

My config file is below:

```
[general]
# Save aggregate and forensic reports to Elasticsearch
save_aggregate = True
save_forensic = True
debug = True
log_file = /var/log/parsedmarc.log

[imap]
# Log into the DMARC report email address and download data.
host = 127.0.0.1
port = 1143
ssl = False
user = test@test.com
password = XxXXXXXX
reports_folder = INBOX/DMARCReports
archive_folder = INBOX/DMARC-Processed
watch = True

[elasticsearch]
# Send data to Elastichsearch, which listens on port 9200.
hosts = 127.0.0.1:9200
ssl = False

[smtp]
# For sending email
host = 127.0.0.1
port = 1025
ssl = False
user = test@test.com
password = XXXXXXXX
from = dmarc@test.com

# send results to this address
to = test@test.com
```

**Comment by ejwensley** [comment]
I am also experiencing this problem. Almost identical config, but the reports_folder is the root of the Inbox.

**Comment by tecman77** [comment]
I am having same issue using msgraph. I've tried with 2 mailboxes so far and latest version of parsedmarc is complaining about "folder INBOX not found". It does however createAggregate/Forensic/Invalid/SMTP-TLS folders under Archive folder just fine.

parsedmarc_1     |     INFO:cli.py:1031:Starting parsedmarc
parsedmarc_1     |    DEBUG:graph.py:134:Folder Archive already exists, skipping creation
parsedmarc_1     |    DEBUG:graph.py:137:Created folder Aggregate
parsedmarc_1     |    DEBUG:graph.py:134:Folder Forensic already exists, skipping creation
parsedmarc_1     |    DEBUG:graph.py:134:Folder SMTP-TLS already exists, skipping creation
parsedmarc_1     |    DEBUG:graph.py:134:Folder Invalid already exists, skipping creation
parsedmarc_1     |    ERROR:cli.py:1323:Mailbox Error
parsedmarc_1     | Traceback (most recent call last):
parsedmarc_1     |   File "/opt/pypy/lib/pypy3.10/site-packages/parsedmarc/cli.py", line 1305, in _main
parsedmarc_1     |     reports = get_dmarc_reports_from_mailbox(
parsedmarc_1     |   File "/opt/pypy/lib/pypy3.10/site-packages/parsedmarc/__init__.py", line 1415, in get_dmarc_reports_from_mailbox
parsedmarc_1     |     messages = connection.fetch_messages(reports_folder, batch_size=batch_size)
parsedmarc_1     |   File "/opt/pypy/lib/pypy3.10/site-packages/parsedmarc/mail/graph.py", line 144, in fetch_messages
parsedmarc_1     |     folder_id = self._find_folder_id_from_folder_path(folder_name)
parsedmarc_1     |   File "/opt/pypy/lib/pypy3.10/site-packages/parsedmarc/mail/graph.py", line 233, in _find_folder_id_from_folder_path
parsedmarc_1     |     return self._find_folder_id_with_parent(folder_name, None)
parsedmarc_1     |   File "/opt/pypy/lib/pypy3.10/site-packages/parsedmarc/mail/graph.py", line 251, in _find_folder_id_with_parent
parsedmarc_1     |     raise RuntimeError(f"folder {folder_name} not found")
parsedmarc_1     | RuntimeError: folder INBOX not found

Version running is: 8.11.0

Any idea how to solve it?

**Comment by pianosaurus** [comment]
@tecman77 
The folder name is set in the `[general]` section of the configuration. You probably want something like this:

```ini
[mailbox]
archive_folder = Inbox/Processed
reports_folder = Inbox
```

Note that Microsoft likes to localize the names of the default folders, so if you have a non-english mailbox, you may need to use another folder name.
