### ISSUE TITLE
Imap Trash

### ISSUE THREAD

**Issue by xennn** [domainaware/parsedmarc#20]
Another Feature Request: Can you add the purge-message command? 
I can only delete the message after parsing the emails. But the mails are in recycle bin and the mailbox is growing.Keep up this good Project :-)

**Comment by seanthegeek** [comment]
Are you using the `--delete` option? That should do it. What mail server are you using?

**Comment by xennn** [comment]
Yes i use the --delete option. We are using Lotus Notes (Domino Server)

**Comment by xennn** [comment]
https://www-01.ibm.com/support/docview.wss?uid=swg21902979

**Comment by seanthegeek** [comment]
Fixed in the 4.2.0 release
