### ISSUE TITLE
No data stored in Elasticsearch

### ISSUE THREAD

**Issue by jurgeng-ot** [domainaware/parsedmarc#209]
I have a fresh install of parsedmarc on Centos 7 (python 3.6).
I have set up a mailbox on my imap server and put a dmarc aggegrate mail in it.
I want parsedmarc to insert the reports into an existing elasticsearch cluster (7.6.2).
When running parsedmarc from the command line, all seems to be working well, except that I don't see any data in Elasticsearch.

Here is my parsedmarc config file:

```
[general]
save_forensic = True
nameservers = 127.0.0.1
debug = true
save_aggegrate = true
offline = true

[imap]
host = mailhost.onetrail.net
user = dmarc-fbl@onetrail.net
password = secret
ssl = true
test = true
watch = false

[elasticsearch]
hosts = onetrail-monaas-elastic-1.cloud.onetrail.net:9200
user = elastic
password = secret
number_of_shards = 3
ssl = false
cert_path = /appserver/parsedmarc/onetrail-monaas-ca.pem
```

When running parsedmarc from the command line, I get these results:

```
0it [00:00, ?it/s]
   DEBUG:__init__.py:1071:Found 2 messages in INBOX
   DEBUG:__init__.py:1075:Processing message 1 of 2: UID 3
   DEBUG:__init__.py:1075:Processing message 2 of 2: UID 4
```
When I check Kibana afterwards, I don't see any data in the dmarc_aggegrate or dmarc_forensic reports. Also the DMARC dashboards in Kibana stay empty.

I don't see anything in the elasticsearch logs.

To test if parsedmarc is actually contacting elasticsearch, I changed the elasticsearch password. Then I got an error from elasticsearch saying '401 unauthorized'. So parsedmarc is contacting elasticsearch and logging in correctly.

Any clue where I can look?

**Comment by bathizte** [comment]
Hello, just in case someone needs a workaround : I had to [install previous release](https://pypi.org/project/parsedmarc/6.11.0/) for parsedmarc to write the indices in elasticsearch !

**Comment by jurgeng-ot** [comment]
Thanks for the tip, but unfortunately, elastic basic auth support was added in 6.12, which I need.

**Comment by MarcusCaepio** [comment]
+1
We just tested parsedmarc 6.12.0 (and also 6.11.0) with Elasticsearch 7.12.0 (SSL and Security enabled). Running with --debug shows the message processing but not a single line about pushing it to elastic. Also elastic is empty, no index is created.

**Comment by steenstra** [comment]
It looks like I'm having the same problem. The dashboard in Grafana stays empty. However, when I run 
`curl -XGET localhost:9200/_search` it shows me the data is in Elasticsearch.
