### ISSUE TITLE
Fail when processing long reports (100kb+, compressed) from IMAP

### ISSUE THREAD

**Issue by maurofaccenda** [domainaware/parsedmarc#219]
When processing messages that takes too long, the IMAP server might disconnect the client. Giving the following output:
```
ERROR:cli.py:623:IMAP Error: socket error: [Errno 32] Broken pipe
```

**Comment by TechieRuss** [comment]
Same here. Is there a way to copy the message and process locally?

**Comment by mback2k** [comment]
I am experiencing the same issue due to a huge report leading to long IMAP delay between individual messages being fetched:
```
Apr 20 10:54:08 parsedmarc[126570]:    DEBUG:__init__.py:1074:Processing message 211 of 2086: UID 168513
Apr 20 10:54:08 parsedmarc[126570]:    DEBUG:__init__.py:1074:Processing message 212 of 2086: UID 168530
Apr 20 11:05:09 parsedmarc[126570]:    DEBUG:__init__.py:1074:Processing message 213 of 2086: UID 170607
Apr 20 11:05:09 parsedmarc[126570]:    ERROR:cli.py:605:IMAP Error: command: FETCH => socket error: EOF
```

**Comment by slv008** [comment]
@mback2k @maurofaccenda any luck with this issue? I tried the your [commit](https://github.com/seanthegeek/mailsuite/pull/5/commits/c499a19ca286e1e1bfb11e32c4fe0f7a371a30ba), @maurofaccenda , but with no luck - the exception is not caught and the connection is still not reseted ...

**Comment by maurofaccenda** [comment]
@slv008 the issue should actually be fixed on the mail library he uses. so i forked this and created a wrapper:

https://github.com/oanda/parsedmarc

You can see the changes here: https://github.com/oanda/parsedmarc/pull/1

**Comment by slv008** [comment]
Thank you @maurofaccenda . It makes sens, but it still throws the same errors even with the wrapper:
`   DEBUG:cli.py:589:Skipping IMAP certificate verification
   DEBUG:__init__.py:1071:Found 1 messages in INBOX
   DEBUG:__init__.py:1075:Processing message 1 of 1: UID 51883
   DEBUG:__init__.py:1127:Moving aggregate report messages from INBOX to Archive/Aggregate
   DEBUG:__init__.py:1134:Moving message 1 of 1: UID 51883
   ERROR:__init__.py:1143:IMAP error: Error moving message UID 51883: [Errno 104] Connection reset by peer
   DEBUG:imapwrapper.py:40:Connection closed by server: (<class 'imaplib.IMAP4.abort'>) socket error: [Errno 32] Broken pipe
   DEBUG:__init__.py:1071:Found 1 messages in INBOX
   DEBUG:__init__.py:1075:Processing message 1 of 1: UID 51883
`

It is odd as it doesn't even try to reset the connection, but it starts all the process all over again

**Comment by maurofaccenda** [comment]
@slv008 i can't reproduce your problem. from the code it should reconnect and try to move the message again. maybe you can add a few debug messages to figure what's going on. sorry i am not able to help much more than suggesting this.

**Comment by slv008** [comment]
@maurofaccenda have a look please at the fix that worked for me. Makes any sense to you?

**Comment by maurofaccenda** [comment]
@slv008 considering how the code looks today, it makes sense.

but to be honest, i think this should be completely refactored. single-responsibility (from https://en.wikipedia.org/wiki/SOLID) should be advised :)

unfortunately i don't have the bandwidth :(
