### ISSUE TITLE
Elasticsearch rollover by mounth GDPR

### ISSUE THREAD

**Issue by xennn** [domainaware/parsedmarc#22]
Hello, can you explain how to rollover the index from Elasticsearch?
Exist there a way to automate this process?

**Comment by xennn** [comment]
I found a solution with a query, but its not automated.

POST /dmarc_aggregate/_delete_by_query
{
  "query": { "match_all": {} }
}

POST /dmarc_forensic/_delete_by_query
{
  "query": { "match_all": {} }
}

**Comment by seanthegeek** [comment]
https://www.elastic.co/blog/managing-time-based-indices-efficiently

**Comment by xennn** [comment]
Thank You!

**Comment by seanthegeek** [comment]
Added link to the documentation

**Comment by xennn** [comment]
Found easy solution with a cronjob

curl -XPOST "http://localhost:9200/dmarc_aggregate/_delete_by_query" -H 'Content-Type: application/json' -d'
{
"query": { "match_all": {} }
}'
