### ISSUE TITLE
index suffix is not used when searching for existing documents.

### ISSUE THREAD

**Issue by drawks** [domainaware/parsedmarc#235]
While doing some testing I noticed that when inserting into elastic search the test to see if a report already exists doesn't use the `index_suffix` parameter from the config. This doesn't feel critical, but it is quite unexpected. When running tests with a known bolus of reports you MUST delete indices between tests and you cannot run tests in parallel with the same test bolus because parsedmarc will refuse to insert reports with identical details.

**Comment by reyjrar** [comment]
FWIW, use of the `index` action in the Bulk API, instead of `create` will allow documents with the same `_id` to be reindexed without throwing an exception.
