### ISSUE TITLE
Allow for limiting the number of messages processed via imap in a given run

### ISSUE THREAD

**Issue by drawks** [domainaware/parsedmarc#238]
When pulling reports over imap as a batch job I'm finding that memory usage is unacceptably high and run times are unpredictably long with a large number of Inbox items. It would be great if there was a flag/option to limit the number of reports that would be pulled over imap in a given run.

**Comment by mback2k** [comment]
I would also appreciate this feature being implemented.

**Comment by tom-henderson** [comment]
I've also submitted #222 a while ago to achieve this.
