### ISSUE TITLE
Tabs in email subjects / filename.

### ISSUE THREAD

**Issue by mikesiegel** [domainaware/parsedmarc#24]
Noticed an issue where some dmarc reports arent being picked up via the IMAP client.

These reports have the subject/filename as ```receiver.com!myorg.com!epoch1!epoch2!dmarc.xml.gz```

These aren't ending up being removed from the mailbox nor send to ES/Kafka.  Processing it right from the file works fine, so I suspect it might be the imapclient? Not seeing any exceptions. I'll dig in deeper when I have some time.

**Comment by mikesiegel** [comment]
Upon further review, I have other dmarc reports with ! in them that parse fine.  I think it's more likely: there is a tab between Report-ID: and their domain.

```Report Domain: myorg.com Submitter: them.com Report-ID:<tab>	them.com!myorg.com!1539468000!1539554400!dmarc```

**Comment by seanthegeek** [comment]
Yep. exclamation points are fine. It's probably the tab. I've never encountered that before. It does not line a bug in imapclient at this point.

**Comment by mikesiegel** [comment]
My bad, it was some pre-filtering on our end.
