### ISSUE TITLE
Kibana visualizations over time show duplicate data

### ISSUE THREAD

**Issue by mwander** [domainaware/parsedmarc#246]
The two Kibana visualizations **DMARC Passage Over Time** and **Message Disposition Over Time** show duplicate data. This is because the x-axis aggregates over `date_range`, which will count each message for both the start and end day.

How it looks:
![over_time_date_begin](https://user-images.githubusercontent.com/3373336/120938943-acaa1380-c715-11eb-9a62-20e4f720899c.png)
How it should look:
![over_time_date_range](https://user-images.githubusercontent.com/3373336/120938944-ad42aa00-c715-11eb-92f6-ae79143e6e5a.png)

Fix:
* Edit visualization
* Change aggregation field from `date_range` to `date_begin` (or `date_end`, whichever you prefer)

**Comment by knightian** [comment]
Yes I am seeing the same problem
