### ISSUE TITLE
Is there any countermeasure for XXE?

### ISSUE THREAD

**Issue by hughwangmail** [domainaware/parsedmarc#253]
I do not understand XXE very well. Just wonder whether there is any countermeasure for XXE in this project?
I will try to test by myself. Please share with me if you have any idea.

**Comment by hughwangmail** [comment]
@seanthegeek . If you have any idea, I am very glad if you can share with me.

**Comment by seanthegeek** [comment]
parsedmarc does not launch any code or comand based on the XML reports, so these is little to no XXE risk.
