### ISSUE TITLE
7.0.1 Splunk HEC not receving if lot of DMARC reports need to be processed

### ISSUE THREAD

**Issue by Idriel** [domainaware/parsedmarc#255]
Hi, parsedmarc had glitch on v6.12 and now we update to 7.01. 
Now we have mailbox folder with 10 000 mail-s and Debug log have output:
Processing message xyz and then:
EEBUG:__init__.py:312:Sending noop cmd
   DEBUG:__init__.py:315:Processed 120/995
   DEBUG:__init__.py:312:Sending noop cmd
   DEBUG:__init__.py:315:Processed 140/995
   DEBUG:__init__.py:312:Sending noop cmd
   DEBUG:__init__.py:315:Processed 160/995
   DEBUG:__init__.py:312:Sending noop cmd
   DEBUG:__init__.py:315:Processed 180/995

None of the log's are sent to Splunk HEC?

**Comment by seanthegeek** [comment]
The reports don't get sent to Splunk HEC or elasticsearch until after all emails are processed.
