### ISSUE TITLE
Dealing with multiple PTR records

### ISSUE THREAD

**Issue by aharpour** [domainaware/parsedmarc#259]
Hi
First, let me start by thanking you for the great library. 

Although most IP addresses resolve to a single PTR record, It is perfectly valid for an IP address to have more than one PTR record. 
Currently, at line 192 of "utils.py", I see this line.

 hostname = query_dns(address, "PTR", cache=cache,
	 nameservers=nameservers,
	 timeout=timeout)[0]

Which I guess is always picks the first PTR record returned from the DNS. I  ran into this case in practice and what actually happens is that DNS doesn't always return the records in the same order. So every time a different PTR record is chosen at random. 
It would be nice if it would always select the same PTR record. I suggest first sorting the record Lexicographically before selecting the first item.

Thank you very much
Ebrahim Aharpour

**Comment by dragoangel** [comment]
multiple PTRs on SMTP server is strange, and I just curious how MTA with such PTR will provide own EHLO?:D
Why exactly first by alphabet record should be taken? Why not last or middle one?

**Comment by seanthegeek** [comment]
SMTP serverd should not have multiple PTR records.
