### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by KLelong** [domainaware/parsedmarc#267]
Hi,
I'm using parsedmarc for a while now and I would like to add a second domain to monitor.
Is there any documentation how to do this ?
At the moment that second domain has a different rua-address than the first, but both are under my control.
I would like to have different graphs in kibana.
Or is there a way in kibana to distinguish the domains, so I could use only one rua-address for those domains ? 
BTW, I don't use ruf at the moment.
TIA

**Comment by ag333** [comment]
.
I would like to know how to do this too.

**Comment by seanthegeek** [comment]
You can have both point to the same rua address, The kibana dashboard will allow you to filter on a specific domain already, by using the from domain list on the far left
