### ISSUE TITLE
number_of_replicas cannot be set without setting number_of_shards

### ISSUE THREAD

**Issue by glade-at-gigwell** [domainaware/parsedmarc#269]
In a simple setup, having 1 shard + 1 replica causes elasticsearch to remain in the YELLOW state.  In order to fix this, we should set the number_of_replicas to 0.  However, the indentation of the settings code currently requires number_of_shards to be defined for it to read the number_of_replicas value.

**Comment by glade-at-gigwell** [comment]
https://github.com/domainaware/parsedmarc/blob/master/parsedmarc/cli.py#L400-L403

**Comment by knightian** [comment]
> https://github.com/domainaware/parsedmarc/blob/master/parsedmarc/cli.py#L400-L403

I did this to set the default to 0 replication I think that makes sense really

https://github.com/domainaware/parsedmarc/pull/274

**Comment by seanthegeek** [comment]
Fixed in PR #274 , which will be included in a release soon.
