### ISSUE TITLE
GeoLite2-Country.mmdb is missing

### ISSUE THREAD

**Issue by fabswt** [domainaware/parsedmarc#270]
Trying to run parsedmarc, here is what I get:

```
 WARNING:utils.py:296:GeoLite2-Country.mmdb is missing. Please follow the instructions at https://dev.maxmind.com/geoip/geoipupdate/ to get the latest version.
 WARNING:utils.py:296:GeoLite2-Country.mmdb is missing. Please follow the instructions at https://dev.maxmind.com/geoip/geoipupdate/ to get the latest version.
 WARNING:utils.py:296:GeoLite2-Country.mmdb is missing. Please follow the instructions at https://dev.maxmind.com/geoip/geoipupdate/ to get the latest version.
 WARNING:utils.py:296:GeoLite2-Country.mmdb is missing. Please follow the instructions at https://dev.maxmind.com/geoip/geoipupdate/ to get the latest version.
 WARNING:utils.py:296:GeoLite2-Country.mmdb is missing. Please follow the instructions at https://dev.maxmind.com/geoip/geoipupdate/ to get the latest version.
 WARNING:utils.py:296:GeoLite2-Country.mmdb is missing. Please follow the instructions at https://dev.maxmind.com/geoip/geoipupdate/ to get the latest version.
 WARNING:utils.py:296:GeoLite2-Country.mmdb is missing. Please follow the instructions at https://dev.maxmind.com/geoip/geoipupdate/ to get the latest version.
```

I'm getting one or more of these warnings with all DMARC reports, including [the example from the DMARC wiki](https://dmarc.org/wiki/FAQ#I_need_to_implement_aggregate_reports.2C_what_do_they_look_like.3F).

I'm getting the warning even if I use the `--offline` flag.

I've installed geoipupdate, its config file, and ran `sudo geoupdate` as per the documentation. But I'm left wondering where the database is, IF it's been downloaded.

Bit lost here. Advice would be welcome.

Thank you!

P.S.: in passing, I think there's a problem with the documentation on pypi.org. https://domainaware.github.io/parsedmarc/ mentions geoipupdate, but https://pypi.org/project/parsedmarc/ does not, even though both have parsedmarc 7.0.1.

**Comment by LiamMcM** [comment]
I had this issue, but realised that I was running v6.12.0. Upgrading to v7.1.1 (via pip3 in my case) solved it.
