### ISSUE TITLE
date_parser.py:35: date_obj = stz.localize(date_obj)

### ISSUE THREAD

**Issue by hydroflash** [domainaware/parsedmarc#273]
date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)

**Comment by lnedry** [comment]
I'm seeing the same warnings in my logs.
