### ISSUE TITLE
using DB-IP instead of Maxmind GeoIP

### ISSUE THREAD

**Issue by wizdude** [domainaware/parsedmarc#275]
since Maxmind has changed their policy several times for the "free" feed of their data, i've found that use of their feed is becoming problematic. 

i had previously used their feed to setup custom firewall rules to block countries for services that I was running, but with Ubuntu 20.04 the scripts included with xtables-addons-common dropped support for Maxmind in favour of DB-IP. this in turn also massively simplified the setup and implementation for this specific use case.

i've been very happy with the feeds from DB-IP. their free feed is licensed under Creative Commons (CC-BY-4.0).

would it be possible to implement their feed instead of the Maxmind one?

**Comment by seanthegeek** [comment]
Great idea! I haven't heard of this database and will look into it.
