### ISSUE TITLE
Publicsuffix

### ISSUE THREAD

**Issue by xennn** [domainaware/parsedmarc#28]
Okt 22 14:44:33 Hostname parsedmarc[10654]: WARNING:parsedmarc:Failed to download an updated PSL HTTPSConnectionPool(host='publicsuffix.org', port=443): Max retries exceeded with url: /list/public_suffix_list.dat (Caused by NewConnection

Parsedmarc try to connet to publixsuffix.org without Proxy.
Can you add a proxy feature? Or i must use a direkt connection rule.

![grafik](https://user-images.githubusercontent.com/7826090/47295636-6e1cc480-d610-11e8-9459-b4f7930a9c4c.png)

**Comment by xennn** [comment]
The Service has a Problem with this too. I must create a cronjob as workaround.

![grafik](https://user-images.githubusercontent.com/7826090/47387656-49a81180-d710-11e8-92be-70f4025545dc.png)

**Comment by seanthegeek** [comment]
Hi.

You need to edit `/etc/environment` and add your proxy details there, for example:

```bash
http_proxy='http://user:password@prox-server:3128
https_proxy='http://user:password@prox-server:3128
ftp_proxy='http://user:password@prox-server:3128
```

Or if no credentials are needed:

```bash
http_proxy='http://prox-server:3128
https_proxy='http://@prox-server:3128
ftp_proxy='http://prox-server:3128
```

**Comment by seanthegeek** [comment]
Innstructions added to installation documentation
