### ISSUE TITLE
V7.0.1 - Slow

### ISSUE THREAD

**Issue by Behner** [domainaware/parsedmarc#280]
I have downgraded to v7.0.0 and everything is back to normal, sub-second processing of reports.

Ubuntu 20.04.3 LTS

save_aggregate = True
save_forensic = True
debug = True
nameservers = [1.1.1.1,8.8.8.8]
silent = False

[imap]
host = imap.gmail.com
port = 993
ssl = True
user = something@gmail.com
password = something
watch = True
reports_folder = DMARC
archive_folder = DMARCarchive

[elasticsearch]
hosts = elastic:9200
ssl = False
index_suffix = parsedmarc
monthly_indexes = True
number_of_shards = 2
number_of_replicas = 1

**Comment by seanthegeek** [comment]
I haven't experienced this. Check the actual 7.1.0 release that was just uploaded to pypi

**Comment by Behner** [comment]
Sorry, it was v7.0.1 I experience this with and I will certainly give 7.1.0 a shot. 

Thank you! @seanthegeek

**Comment by seanthegeek** [comment]
Glad to hear it
