### ISSUE TITLE
No info about updating ParseDMARC

### ISSUE THREAD

**Issue by davidande** [domainaware/parsedmarc#283]
hello,
I would like to update Parsedmarc to the latest stable version.
Someone could please tell me how to do it?
parsdmarc is installed on Ubuntu Desktop (no docker)
thanks
David

**Comment by leonardo0014** [comment]
try with `sudo pip install -U parsedmarc` or alternatively with the version information `sudo pip install -U parsedmarc==7.1.1`

**Comment by davidande** [comment]
Thanks It works
