### ISSUE TITLE
Kibana/Elasticsearch "sample.headers.sender.keyword" no longer exists

### ISSUE THREAD

**Issue by vestaxb** [domainaware/parsedmarc#290]
Hello,

at first I'd like to say thank you for all your effort in parsedmarc. It is a great tool!

I have this little warning message in the DMARC forensic samples dashboard. 

_[esaggs] The field "sample.headers.sender.keyword" associated with this object no longer exists in the index pattern. Please use another field._

![image](https://user-images.githubusercontent.com/98818909/151968697-56c8656c-5c0d-4323-8116-8e0b18ae1908.png)

Could somebody help me to get rid of this message so the samples are displayed correctly?

Thank you!

**Comment by droobah** [comment]
I "fixed" this on my instance by editing the Forensic Samples Data Table in the Visualize Library.  

Two buckets had errors.  I switched sample.headers.sender.keyword to sample.headers.from.keyword and sample.headers.reply-to.keyword to sample.headers.return-path.keyword.

I'm unsure if these are the fields that should be used, but it was enough to get the widget to load and provides the information we needed.

**Comment by davidande** [comment]
Hello,
I also modified the Forensic Sample Data Table. Ok for the fisrt modification.  for the second one, I was not able to find sample.headers.return-path.keyword.  I switched it to sample.headers.return-receipt-to.keyword. and it works

**Comment by Hexamailman** [comment]
Hello,

I have the same problem with some bucket that are missing source_base_

Any solution to this ?

**Comment by Hexamailman** [comment]
Hello,

In my case, I found for the fields source_base_ that it didn't exist because my Parsedmarc server tried to make nslookup but my firewall was blocking its requests. Since I authorize my server to go through the firewall, the fields became visible and filled (not for the older, but for all the new reports). I don't know for the field sample.headers but I hope it can help.

Best regards

**Comment by seanthegeek** [comment]
Make sure your firewalls allow the server to make DNS requests for PTR records.
