### ISSUE TITLE
Installation guide needed

### ISSUE THREAD

**Issue by davidande** [domainaware/parsedmarc#295]
Hello,
I was using Parsedmarc on Ubuntu 20.04 on a VM. Everything was working fine since I did the update to 7.1.1.
For info, I use 365 in IMAP and all was working fine till mid february (my update)
Now all the reports stay in the inbox and nothing new is coming in parsedmarc.
I used two documentations. The one from domaineware and onother dedicated for ubuntu
https://domainaware.github.io/parsedmarc/
https://www.linuxbabe.com/mail-server/parsedmarc-ubuntu-20-04

I'm not feeling very confortable with linux ans I wlould like to know if You know where to find a complète step by step doc that is working.

In advance thanks for your help

David

**Comment by davidande** [comment]
it's ok I did some investigations and tests. everything is ok mixing different sources

**Comment by Lefty1984** [comment]
What kind of VM did you use? With a GUI or Headless?
