### ISSUE TITLE
Processing of accumulated reports is intransparent and a bit error-prone

### ISSUE THREAD

**Issue by volter** [domainaware/parsedmarc#299]
We had issues with our installation of parsedmarc and didn't bother to fix it for a long time, so a huge lot of reports had accumulated in the mailbox it is configured to process.

After we had parsedmarc up and running again, it started processing, but seemingly created no output. Some strace-ing revealed that it only seems to go to Elasticsearch once _all_ reports are processed, which might take hours and I'm not sure if it could result in a request to ES that could be problematic. I would recommend to introduce some batching instead of waiting until the very end.

What is worse, if you stop parsedmarc, nothing is written to ES, but the reports have been moved to the IMAP folder for reports already processed. I think some signal handling is missing here.

**Comment by davidande** [comment]
I had the same thing happend with 3500 reports in my inbox. You have the choice to wait till the integration process finish (and it is very long or, you can add batch_size = 10 in the IMAP section of your parsedmarc.ini; it will so parse mails 10 by 10.
check sudo parsedmarc -debug /etc/parsedmarc.ini  to check the proccess

**Comment by volter** [comment]
Ah, OK, that's good to know, thanks. The whole thing is a bit of a corner case, of course. Maybe that could be a sensible default setting.

**Comment by davidande** [comment]
by the way, if you have started the integration process witout batch_size, just wait for the proccess to end. in my case it tokks hours!!!

**Comment by volter** [comment]
Yes, sure, you could do that, but to an unknowing new user it looks like it's just not working and if they cancel it, having no data seems to confirm that.

**Comment by davidande** [comment]
yes and if you cancel or reboot, the whole process of integration start again from scratch

**Comment by volter** [comment]
That's not exactly the behaviour that I think to have witnessed, as parsed (but not saved) messages were already moved to a folder, so that I think they would not be considered again.

**Comment by bendem** [comment]
> That's not exactly the behaviour that I think to have witnessed, as parsed (but not saved) messages were already moved to a folder, so that I think they would not be considered again.

This is #242
