### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by thomaskalombo** [domainaware/parsedmarc#305]
Hello everyone,
i just install with the following commands from a tuto, but i'm getting the error in subject

########### Installing Docker on Ubuntu
sudo apt update
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update
apt-cache policy docker-ce
sudo apt install docker-ce
sudo systemctl status docker

############ Install Docker compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version

############ Running Hello World
sudo docker run hello-world

############ Running the YML file
sudo docker-compose up -d
sudo docker-compose up

**Comment by nathanthorpe** [comment]
This doesn't seem to be related to parsedmarc?

**Comment by seanthegeek** [comment]
Agreed
