### ISSUE TITLE
Please make parsedmarc compatible with current Elasticsearch versions.

### ISSUE THREAD

**Issue by hunter-nl** [domainaware/parsedmarc#329]
Grafana 9 does not support Elasticsearch EOL versions. Parsedmarc does not work with not EOL versions of Elasticsearch.
Is it possible to make Parsedmarc compatible with current Elasticsearch versions?

**Comment by nathanthorpe** [comment]
I'm using the latest version of Elasticsearch (8.2.3) with parsedmarc. Could you describe your issue a bit more?

**Comment by hunter-nl** [comment]
My elasticsearch database got corrupted with the upgrade migration. I've reinstalled it and it is now working again with de latest versions.
