### ISSUE TITLE
Reports not pulled during Idle

### ISSUE THREAD

**Issue by RockSlice** [domainaware/parsedmarc#33]
Configuration: My DMARC reports are going to a folder/label in a G Suite email account.
parsedmarc version: 4.4.1

When parsedmarc starts, it grabs all the reports properly.

However, any subsequent reports will sit unread while parsedmarc keeps refreshing the IDLE session.  During this period, new (unrelated) emails have arrived in the Inbox.

**Comment by seanthegeek** [comment]
This has been fixed in `parsedmarc` 5.0.0.

**Warning**: Re-importing `kibana_saved_objects.json` in Kibana [is required](https://domainaware.github.io/parsedmarc/#upgrading-kibana-index-patterns) when upgrading to this version!
