### ISSUE TITLE
Using MS Graph can't find INBOX

### ISSUE THREAD

**Issue by calmicoder** [domainaware/parsedmarc#351]
I'm trying to switch from using IMAP to MSGraph since Microsoft will be turning off Basic Auth to Exchange Online starting next month.

I've created a new app in azure and assigned it application mail.readwrite

my parsedmarc.ini has the following:
[msgraph]
auth_method = ClientSecret
mailbox = mailbox@domain
client_id = appid
client_secret = appsecret
tenant_id = tenantid

I'm getting the following error when running parsedmarc:
 INFO:cli.py:777:Starting parsedmarc
DEBUG:graph.py:121:Folder Archive already exists, skipping creation
DEBUG:graph.py:121:Folder Aggregate already exists, skipping creation
DEBUG:graph.py:121:Folder Forensic already exists, skipping creation
DEBUG:graph.py:121:Folder Invalid already exists, skipping creation
ERROR:cli.py:969:Mailbox Error: folder INBOX not found

**Comment by nathanthorpe** [comment]
It is case sensitive, so try using:

```
[mailbox]
reports_folder = Inbox
```

**Comment by calmicoder** [comment]
I added those lines to parsedmarc.ini and now I get this error instead:
ERROR:cli.py:969:Mailbox Error: 'value'

**Comment by nathanthorpe** [comment]
Maybe #352  will help troubleshoot

**Comment by calmicoder** [comment]
All that seemed to do was change the error message without any additional information.
ERROR:cli.py:969:MailBox Error

**Comment by calmicoder** [comment]
Any other ideas on getting this working?

**Comment by nathanthorpe** [comment]
I was able to reproduce it. I've added my changes in the #352 PR. In the meantime, try to add the `batch_size` parameter in your config.

**Comment by calmicoder** [comment]
adding this section fixed my issue.  Thanks for your help.

`[mailbox]
report_folder = Inbox
batch_size = 0`
