### ISSUE TITLE
Using Azure Event Hub

### ISSUE THREAD

**Issue by DanPerfect** [domainaware/parsedmarc#37]
I'm trying to use Azure Event Hub which can act as a Kafka endpoint. This is the command:

sudo parsedmarc --save-aggregate --save-forensic -H "{hostname}" -u "{user}" -p "{password}" -K "{Event Hub Connection String}" --test --debug 

The Event Hub Connection String is an endpoint URL that contains the endpoint hostname, access key and topic. I get the following error:

ERROR:parsedmarc:Kafka Error: encoding with 'idna' codec failed (UnicodeError: label too long)
ERROR:parsedmarc:Kafka Error: local variable 'kafka_client' referenced before assignment
ERROR:parsedmarc:Kafka Error: local variable 'kafka_client' referenced before assignment
ERROR:parsedmarc:Kafka Error: local variable 'kafka_client' referenced before assignment
(This local variable error repeats as for each message the mailbox)

**Comment by seanthegeek** [comment]
I've started work on this, but ran into a problem with the module I use. 

https://github.com/dpkp/kafka-python/issues/1662

**Comment by seanthegeek** [comment]
Hmmm. Looks like that field got mapped to the `date` type, even though I explicitly set the field to be a `date_range` type in Python. Weird.

```json
{
  "mapping": {
    "doc": {
      "properties": {
        "date_range": {
          "type": "date"
        },
```

**Comment by seanthegeek** [comment]
Upstream bug in kafka-python
