### ISSUE TITLE
Registering the app in MS Graph

### ISSUE THREAD

**Issue by dmiljk** [domainaware/parsedmarc#370]
Hi everyone,

I don't have experience with MS Graph but I have to use it. I went to register parsedmarc as an application in order to be able to access mailbox on MS365, but I have no clue what Redirect URI I'm supposed to enter during the registration of the application?! Any advice would be much appreciated.

**Comment by gijsvanlokven** [comment]
Hey! Thanks for checking out this project.

You don't need a redirect URL. Just simply enter a name for your app registration and save it. It'll give you the client and tenant ID you need. 

Let me know if you need any more help!

**Comment by dmiljk** [comment]
Hi Gijs,

Thank you for the reply and thank you for this usefull project!

I’m struggling a bit with installing it and configuration, but I figured out in the meantime that that field can actually be left blank. I’ve managed to authentication via MS Graph and make parsedmarc collect email reports.

Right now I’m trying to figure out why I’m getting error “FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmposh9r7kj/aggregate.json'” when I enable email of the parsedmarc repots, but I guess that’s for another topic. :)

Thanks again!
