### ISSUE TITLE
documentation / installation

### ISSUE THREAD

**Issue by Pascal76** [domainaware/parsedmarc#379]
on https://domainaware.github.io/parsedmarc/:

"sudo -u parsedmarc /opt/parsedmarc/venv -U parsedmarc"
do you mean  "sudo -u parsedmarc /opt/parsedmarc/venv/bin/pip install -U parsedmarc"

?

**Comment by AnaelMobilia** [comment]
Hello @Pascal76 

Yes, there is a typo on the install doc.
PR #361 is already open for this issue, the doc will be fixed as soon it will be merged.
Note : you may need to activate your venv too (see PR).

Bests regards,
Anael

**Comment by AnaelMobilia** [comment]
This issue could be closed as resolved by #361 (ping @seanthegeek )
