### ISSUE TITLE
Occasional 'corrupt' message

### ISSUE THREAD

**Issue by DanPerfect** [domainaware/parsedmarc#38]
Every now and again I get a 'corrupt' message in my dmarc reporting mailbox and the parser fails with the below errors. I clear the offending email and it all starts working again. Not sure how I can share the message with you, but they have an attachment called 'eml' and that's it. It's certainly not a proper dmarc report xml.

Another question. Do you have a recommendation on server specs for running this? DMARC is configured to report back on 1% on email and I find the reports from Google take up to 3 hours to process. This is ~450k emails, so we'd be talking 4.5 million if I take that up to 100% of emails being reported...

Dec 04 10:46:35 dmarc-proc systemd[1]: parsedmarc.service: Failed with result 'exit-code'.
Dec 04 10:46:35 dmarc-proc systemd[1]: parsedmarc.service: Main process exited, code=exited, status=1/FAILURE
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]: parsedmarc.ParserError: Unexpected error: 'NoneType' object has no attribute 'isoformat'
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:     raise ParserError(e.__str__())
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:   File "/opt/venvs/parsedmarc/site-packages/parsedmarc/__init__.py", line 718, in parse_report_email
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:     strip_attachment_payloads=sa)
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:   File "/opt/venvs/parsedmarc/site-packages/parsedmarc/__init__.py", line 1001, in get_dmarc_reports_f
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:     strip_attachment_payloads=sa
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:   File "/opt/venvs/parsedmarc/site-packages/parsedmarc/cli.py", line 321, in _main
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:     sys.exit(_main())
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:   File "/usr/local/bin/parsedmarc", line 11, in <module>
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]: Traceback (most recent call last):
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]: During handling of the above exception, another exception occurred:
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]: parsedmarc.InvalidForensicReport: Unexpected error: 'NoneType' object has no attribute 'isoformat'
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:     "Unexpected error: {0}".format(error.__str__()))
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:   File "/opt/venvs/parsedmarc/site-packages/parsedmarc/__init__.py", line 599, in parse_forensic_repor
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:     strip_attachment_payloads=strip_attachment_payloads)
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:   File "/opt/venvs/parsedmarc/site-packages/parsedmarc/__init__.py", line 716, in parse_report_email
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]: Traceback (most recent call last):
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]: During handling of the above exception, another exception occurred:
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]: AttributeError: 'NoneType' object has no attribute 'isoformat'
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:     parsed_report["arrival_date"] = msg_date.isoformat()
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]:   File "/opt/venvs/parsedmarc/site-packages/parsedmarc/__init__.py", line 530, in parse_forensic_repor
Dec 04 10:46:35 dmarc-proc parsedmarc[19229]: Traceback (most recent call last):
Dec 04 10:46:30 dmarc-proc systemd[1]: Started parsedmarc mailbox watcher.

**Comment by JayBuckley7** [comment]
I have a sender whose attachments always make parsedmarc hang as well.

**Comment by seanthegeek** [comment]
@DanPerfect @JayBuckley7 Can either of you send me samples at seanpw@pm.me so I can reproduce the issue?

**Comment by seanthegeek** [comment]
@JayBuckley7 Can you provide more details in a separate issue?

@DanPerfect This issue will be fixed in the next release, as soon as I fix a couple IMAP bugs
