### ISSUE TITLE
parsedmarc exits with unexpected internal exception

### ISSUE THREAD

**Issue by LoserFriendly** [domainaware/parsedmarc#39]
Today I've noticed in the syslog that parsedmarc service is exiting repeatedly. What happens right now is that service is restarted after exiting, there is an IMAP check (but the inbox of the user which collects the DMARC logs is empty) and after about one minute it exits again.

Dec  5 14:07:09 smtp-test systemd[1]: parsedmarc.service: Service hold-off time over, scheduling restart.
Dec  5 14:07:09 smtp-test systemd[1]: parsedmarc.service: Scheduled restart job, restart counter is at 20.
Dec  5 14:07:09 smtp-test systemd[1]: Stopped parsedmarc mailbox watcher.
Dec  5 14:07:09 smtp-test systemd[1]: Started parsedmarc mailbox watcher.
Dec  5 14:07:13 smtp-test dovecot: imap-login: Login: user=<dmparser>, method=PLAIN, rip=192.168.206.71, lip=192.168.206.71, mpid=17323, secured, session=<hEt+D0Z89L/AqM5H>
Dec  5 14:08:08 smtp-test parsedmarc[17299]: RPython traceback:
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "pypy_interpreter.c", line 38745, in BuiltinCode2_fastcall_2
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "pypy_module__io_1.c", line 15945, in W_BufferedReader_readline_w
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "implement_2.c", line 47370, in dispatcher_69
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "pypy_module__io.c", line 16566, in W_BufferedReader__raw_read_1
Dec  5 14:08:08 smtp-test parsedmarc[17299]: Traceback (most recent call last):
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "/usr/local/bin/parsedmarc", line 11, in <module>
Dec  5 14:08:08 smtp-test parsedmarc[17299]:     sys.exit(_main())
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "/opt/venvs/parsedmarc/site-packages/parsedmarc/cli.py", line 373, in _main
Dec  5 14:08:08 smtp-test parsedmarc[17299]:     dns_timeout=args.timeout, strip_attachment_payloads=sa)
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "/opt/venvs/parsedmarc/site-packages/parsedmarc/__init__.py", line 1527, in watch_inbox
Dec  5 14:08:08 smtp-test parsedmarc[17299]:     responses = server.idle_check(timeout=wait)
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "/opt/venvs/parsedmarc/site-packages/imapclient/imapclient.py", line 156, in wrapper
Dec  5 14:08:08 smtp-test parsedmarc[17299]:     return func(client, *args, **kwargs)
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "/opt/venvs/parsedmarc/site-packages/imapclient/imapclient.py", line 795, in idle_check
Dec  5 14:08:08 smtp-test parsedmarc[17299]:     line = self._imap._get_line()
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "/opt/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/imaplib.py", line 1133, in _get_line
Dec  5 14:08:08 smtp-test parsedmarc[17299]:     line = self.readline()
Dec  5 14:08:08 smtp-test parsedmarc[17299]:   File "/opt/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/imaplib.py", line 297, in readline
Dec  5 14:08:08 smtp-test parsedmarc[17299]:     line = self.file.readline(_MAXLINE + 1)
Dec  5 14:08:08 smtp-test parsedmarc[17299]: SystemError: unexpected internal exception (please report a bug): <BlockingIOError object at 0x7fe88a727d40>; internal traceback was dumped to stderr
Dec  5 14:08:08 smtp-test dovecot: imap(dmparser): Connection closed (IDLE running for 0.001 + waiting input for 25.045 secs, 0.001 in locks, 2 B in + 10 B out, state=wait-input) in=295 out=1675
Dec  5 14:08:08 smtp-test systemd[1]: parsedmarc.service: Main process exited, code=exited, status=1/FAILURE
Dec  5 14:08:08 smtp-test systemd[1]: parsedmarc.service: Failed with result 'exit-code'.
Dec  5 14:08:08 smtp-test dovecot: imap(dmparser): Connection closed (UID SEARCH finished 55.139 secs ago) in=240 out=1233

The server is Ubuntu 18.04.1, parsedmarc 5.1.0, pypy3.5-6.0.0-linux_x86_64-portable and the service command line is:
/usr/local/bin/parsedmarc --watch --silent -H <host> -u dmparser -p <password> --imap-no-ssl --elasticsearch-index-suffix unitntest --save-aggregate --save-forensic -n <internal DNS>

**Comment by seanthegeek** [comment]
This looks like a bug in pypy imaplib. Have you tried with normal Python 3?

**Comment by LoserFriendly** [comment]
> This looks like a bug in pypy imaplib. Have you tried with normal Python 3?

I've tried, but I couldn't get it to work. The cli could create the indexes in Elasticsearch, but they were empty. An example of what the output was:
DEBUG:parsedmarc:Creating Elasticsearch index: dmarc_aggregate-2018-11-21
ERROR:parsedmarc:Elasticsearch Error: Elasticsearch error: Range accepts a single dictionary or a set of keyword arguments.
This was the output for every message parsed.

That's why I've tried the pypy approach. Moreover, using pypy and the virtual env speeds up the message parsing a lot (but this is probably normal).
The parsedmarc cli is working fine anyway, even if the service is restarted every 7-8 minutes. Please let me know if I can provide any further information, all in all it's a non blocking issue and maybe there's no need of further investigation.

**Comment by seanthegeek** [comment]
Upsteam bug in pypi's imaplib. Cannot reproduce.
