### ISSUE TITLE
[WINDOWS] Map of Message Source countrie empty

### ISSUE THREAD

**Issue by davidande** [domainaware/parsedmarc#391]
Hello,
Windows serveur 2022
Python 3.10.10
Elasticsearch and Kibana 8.6.2

The map stay empty evn if Ip's are well located
![image](https://user-images.githubusercontent.com/22703387/224503369-3558026b-15c4-4c64-bd39-b3ab8ec2894b.png)

Any idea?

**Comment by davidande** [comment]
It seems that Kibana change the way to manage map visualization. It ask to switch from Map to Maps. I had to create a new layer.

**Comment by urbaned121** [comment]
Hi, any progress on it? :)
