### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by MeowyMeowy** [domainaware/parsedmarc#4]
Recreated same issues when installing via using both methods described in instructions (straight install and install via Git).  Installer fails with below issue:

Collecting publicsuffix (from parsedmarc==3.7.2)
  Using cached https://files.pythonhosted.org/packages/76/8e/2be900ba8397bafe88c9d17fab456faddab7af22d7105df18699d3dd97de/publicsuffix-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zl_4wfaa/publicsuffix/setup.py", line 19, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-build-zl_4wfaa/publicsuffix/setup.py", line 13, in get_long_description
        read_doc("LICENSE")
      File "/tmp/pip-build-zl_4wfaa/publicsuffix/setup.py", line 7, in read_doc
        return open(os.path.join(os.path.dirname(__file__), name)).read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    **_UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 23: ordinal not in range(128)_**

    ----------------------------------------
**_Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zl_4wfaa/publicsuffix/_**

Install attempted using Debian on Windows Subsystem for Linux
x> uname -vrma
x> Linux laptop 4.4.0-17134-Microsoft #1-Microsoft Tue Apr 10 18:04:00 PST 2018 x86_64 GNU/Linux

**Comment by seanthegeek** [comment]
Hi. This is really weird. The installation issue is with `publicsuffix`, one of the dependencies of `parsedmarc`, but [that package hasn't changed since 2015](https://pypi.org/project/publicsuffix/#history). Installation works fine on my systems and in [the Python 3.5 CI tests](https://travis-ci.org/domainaware/parsedmarc/jobs/414630073).

What version of `pip` is installed?

> pip3 --version

**Comment by seanthegeek** [comment]
I just tested the install on a fresh Debian stable (9.5/Stretch) VM, and it worked.

Python 3.5.3
pip 9.0.1

I also tested on Debian testing on Windows Subsystem for Linux

Python 3.6.6
pip 9.0.1

**Comment by JeroenvO** [comment]
Same issue here on debian 9 fresh install (lxc), python3.5.3, pip9.0.1.
How about changing to https://pypi.org/project/publicsuffix2/ ?

```  Using cached https://files.pythonhosted.org/packages/76/8e/2be900ba8397bafe88c9d17fab456faddab7af22d7105df18699d3dd97de/publicsuffix-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w2mlanoe/publicsuffix/setup.py", line 19, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-build-w2mlanoe/publicsuffix/setup.py", line 13, in get_long_description
        read_doc("LICENSE")
      File "/tmp/pip-build-w2mlanoe/publicsuffix/setup.py", line 7, in read_doc
        return open(os.path.join(os.path.dirname(__file__), name)).read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 23: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-w2mlanoe/publicsuffix/```
