### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by hvdkooij** [domainaware/parsedmarc#40]
Thist note could use  a small update.

_Warning
The default JVM heap size for Elasticsearch is very small (1g), which will cause it to crash under a heavy load. To fix this, increase the minimum and maximum JVM heap sizes in /etc/elasticsearch/jvm.options to more reasonable levels, depending on your server’s resources.
Always set the minimum and maximum JVM heap sizes to the same value. For example, to set a 4 GB heap size, set
-Xms4g
-Xmx4g
See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html for more information._

I would add here:

**Make sure the hostmachine has (at least) 2 GB more RAM then the assigned JVM HEAP size.**

**Comment by seanthegeek** [comment]
Done. Thanks!
