### ISSUE TITLE
Split documentation into multiple files

### ISSUE THREAD

**Issue by thatvideoshopguy** [domainaware/parsedmarc#401]
Currently, the documentation is contained in a single [index.md](https://github.com/domainaware/parsedmarc/blob/master/docs/source/index.md) file. To improve the organisation and readability of the documentation, I suggest splitting the content into multiple files. This will make it easier for users to navigate and maintain the documentation in the long run.

### Proposed structure

To start, we'd split out all the `Header 2` labelled section into different files. Then possibly refactor further, if need be. For instance, we'd have `features.md`, `resources.md`, `cli-help.md` etc.

### Notes

Please consider this suggestion to enhance the documentation experience for users and contributors. I'd be happy to tackle this issue, if you assign it to me.

**Comment by bencomp** [comment]
I fully agree with this (and with #402, which might make managing multiple files easier too).
A few weeks ago I started splitting the single index file into several files locally, but I got distracted. My goal was to see if the table of contents sidebar in the rendered documentation would not collapse every time you navigate.

Seeing your issue I finished this initial work and created a draft PR for the branch: #404.
