### ISSUE TITLE
Elasticsearch monthly indexes

### ISSUE THREAD

**Issue by vitalvas** [domainaware/parsedmarc#41]
Need create mechanism for switch between daily and monthly indexes.

In "home" usage - I receiving 3-5 reports every day. Using monthly index is more effective than daily.

**Comment by seanthegeek** [comment]
I'm including this in 5.2.0, which will be released on PyPI as soon as I finish fixing a couple bugs

**Comment by seanthegeek** [comment]
Released in 5.2.0
