### ISSUE TITLE
export.ndjson fails to import

### ISSUE THREAD

**Issue by abottorff** [domainaware/parsedmarc#422]
When importing the export.ndjson, I get this error 

`The file could not be processed due to error: "Unprocessable Entity: Document "79544470-313a-11e8-a742-83431eb55d58" has property "index-pattern" which belongs to a more recent version of Kibana [7.11.0]. The last known version is [7.6.0]"`

I'm running 7.10.2, so I assume the version is not updated enough. Is there a way to make this compatible with 7.10.2? I'm not able to upgrade to a newer version due to AWS wanting to force opensearch after 7.10.2. I did try to force the versions in the export.ndjson but that broke the dashboards

**Comment by robonilha** [comment]
I've ran into a similar issue, where the export.ndjson wouldn't import, but I had a generic error.

For me using the previous version worked out. You should give it a try :)

**Comment by abottorff** [comment]
Forgot to get back to you on this but using the previous committed version worked like a charm. Thanks!
