### ISSUE TITLE
Not working with python 12?

### ISSUE THREAD

**Issue by Zoey2936** [domainaware/parsedmarc#438]
See here: https://github.com/ZoeyVid/parsedmarc-dockerized/actions/runs/6389905573/job/17806282298

**Comment by seanthegeek** [comment]
That is a compatibility issue with one of the build dependencies, not `parsedmarc` itself.

> 38.96 Failed to build aiohttp
> 38.96 ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects
