### ISSUE TITLE
Add Transport Authentication

### ISSUE THREAD

**Issue by orbitroom** [domainaware/parsedmarc#439]
I recently setup my TLS certificates and I was receiving a 401 error. This was due to the username and password being required to authenticate.

I followed this guide but using the file located in my venv folder and it fixed my issue.

https://rootkey.tistory.com/113

**Comment by AnaelMobilia** [comment]
@orbitroom 
parsedmarc manage the authentication, but the doc looks like having an issue.

You can add on you config file : 
```
[elasticsearch]
...
user = xxx
password = xxx
```

@seanthegeek on [3d0f7c8 (7.0.0 release)](https://github.com/domainaware/parsedmarc/commit/3d0f7c8c83ee4098e1bcaa95d82f995d7c9c9bd6#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c4680dfa534) you remove from the doc 3 fields for elasticsearch : user, password and timeout .

These fields are [still parsed on cli.py](https://github.com/domainaware/parsedmarc/blob/95954c5d870a296fb0459abbfdb966700dcac3d9/parsedmarc/cli.py#L592) .

I think we can add again the 3 fields on the documentation (I can made the PR if you want). Your opinion ?

Bests regards,
Anael
