### ISSUE TITLE
indefinite hang on forensic email

### ISSUE THREAD

**Issue by JayBuckley7** [domainaware/parsedmarc#44]
I've noticed you pushed an update to hand bad forensic email a bit ago, I have a sender whose emails always cause parsedmarc to hang until I move that email out of it's way. It's got 3 attachemnts 
a seemily empty .msg file and two .file attachments like these
`====================================`
ATT00001.file
Feedback-Type: auth-failure
User-Agent: szn-mime/2.0.41
Version: 1
Original-Rcpt-To: baart@seznam.cz
Source-Ip: 24.42.59.243
Authentication-Results: email.seznam.cz 1;
	spf_align=fail;
	dkim_align=fail
Delivery-Result: reject
`===============================`
ATT00003.file
Arrival-Date: Sun, 06 Jan 2019 22:36:18 +0100
Reporting-MTA: dns; email.seznam.cz

Final-Recipient: rfc822; `=========`@`=======`.com
Status: 2.0.0
Diagnostic-Code: x-uknown;
Action: x-unknown
Original-Recipient: rfc822; baart@seznam.cz

**Comment by seanthegeek** [comment]
Hi. Please forward the report email to infosecdemo42@gmail.com, so I can reproduce the issue.

**Comment by JayBuckley7** [comment]
on their way

**Comment by seanthegeek** [comment]
Those messages didn't cause any hanging when I ran the scripts on the demo Gmail account. I noticed your fork is 285 commits behind.

Please try using the latest version, that I just released.

**Comment by JayBuckley7** [comment]
Sorry. My brain I guess forgot that code had to compile for the computer to run it, I've been pulling down updates but never actually build them It never even occurred to me that I should really check the -ver. You are right, I've been on 4.3.8 for a long time. Thank you very much.

**Comment by seanthegeek** [comment]
@JayBuckley7  Since you were running a version lower than 5.0.0, be sure to follow the Kibana migration steps here https://domainaware.github.io/parsedmarc/#upgrading-kibana-index-patterns
