### ISSUE TITLE
IMAP Connection timeout

### ISSUE THREAD

**Issue by mfritts** [domainaware/parsedmarc#46]
I've been running parsedmarc as a service for several months. It's working well with the kibana dashboard. But I'm having a problem now that I'm getting about 200 reports a day. Is there a way to run in batches of 10 messages or so? My mail server is timing out and closing the connection before the reports can be archived. If I could run in batches or at least archive the messages that it's already processed instead of starting over when it sees more messages have arrived in the inbox before the last run is finished I think I could get around my timeout issue.
But I'm also looking into other ideas for dealing with this, like running on more than one inbox and process, to reduce the load. Maybe you have some suggestions if no changes to the script?
Great tool, though! I've been pretty happy so far which is why I increased the work that it was doing so much. lol.

From the logs:
Jan 23 14:04:45 mtk-unms-srv01 parsedmarc[8919]: ERROR:parsedmarc:IMAP error: Error moving message UID 6447: socket error: [Errno 32] Broken pipe
Jan 23 14:04:45 mtk-unms-srv01 parsedmarc[8919]: ERROR:parsedmarc:IMAP error: Error moving message UID 6448: socket error: [Errno 32] Broken pipe
Jan 23 14:04:45 mtk-unms-srv01 parsedmarc[8919]: ERROR:parsedmarc:IMAP error: Error moving message UID 6449: socket error: [Errno 32] Broken pipe
Jan 23 14:04:45 mtk-unms-srv01 parsedmarc[8919]: ERROR:parsedmarc:IMAP error: Error moving message UID 6450: socket error: [Errno 32] Broken pipe
Jan 23 14:04:45 mtk-unms-srv01 parsedmarc[8919]: ERROR:parsedmarc:IMAP error: Error moving message UID 6451: socket error: [Errno 32] Broken pipe
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: Traceback (most recent call last):
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: File "/usr/local/bin/parsedmarc", line 11, in
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: sys.exit(_main())
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: File "/usr/local/lib/python3.6/dist-packages/parsedmarc/cli.py", line 321, in _main
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: strip_attachment_payloads=sa
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: File "/usr/local/lib/python3.6/dist-packages/parsedmarc/init.py", line 1162, in get_dmarc_reports_from_inbox
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: results=results
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: File "/usr/local/lib/python3.6/dist-packages/parsedmarc/init.py", line 1162, in get_dmarc_reports_from_inbox
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: results=results
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: File "/usr/local/lib/python3.6/dist-packages/parsedmarc/init.py", line 1162, in get_dmarc_reports_from_inbox
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: results=results
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: [Previous line repeated 11 more times]
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: File "/usr/local/lib/python3.6/dist-packages/parsedmarc/init.py", line 979, in get_dmarc_reports_from_inbox
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: ["RFC822"])[message_uid][b"RFC822"]
Jan 23 14:21:40 mtk-unms-srv01 parsedmarc[8919]: KeyError: 6448
Jan 23 14:21:40 mtk-unms-srv01 systemd[1]: parsedmarc.service: Main process exited, code=exited, status=1/FAILURE
Jan 23 14:21:40 mtk-unms-srv01 systemd[1]: parsedmarc.service: Failed with result 'exit-code'.
Jan 23 14:26:40 mtk-unms-srv01 systemd[1]: parsedmarc.service: Service hold-off time over, scheduling restart.
Jan 23 14:26:40 mtk-unms-srv01 systemd[1]: parsedmarc.service: Scheduled restart job, restart counter is at 3.
Jan 23 14:26:40 mtk-unms-srv01 systemd[1]: Stopped parsedmarc mailbox watcher.
Jan 23 14:26:40 mtk-unms-srv01 systemd[1]: Started parsedmarc mailbox watcher.
Jan 23 15:26:26 mtk-unms-srv01 parsedmarc[31307]: ERROR:parsedmarc:IMAP error: IMAP error: Skipping message UID 6662: socket error: [Errno 104] Connection reset by peer
Jan 23 15:26:26 mtk-unms-srv01 parsedmarc[31307]: ERROR:parsedmarc:IMAP error: IMAP error: Skipping message UID 6663: socket error: [Errno 32] Broken pipe

**Comment by seanthegeek** [comment]
Try the latest dev release i just pushed to Github. It uses a separate IMAP connection for moving/deleting the messages. Let me know how it goes.

To install it, run:

```bash
sudo -H pip3 install -U git+https://github.com/domainaware/parsedmarc.git
```

If you are running `parsedmarc` as a service, restart it:

```bash
sudo service parsedmarc restart
```

**Comment by seanthegeek** [comment]
I had to revert the separate connection for moving email. Office365 really hates multiple concurrent connections from the same host.

That said, I do have some tips on avoiding the timeout,

- Use the `-w`/`--wait` CLI option, this will monitor and process emails as they show up in the inbox, rather than processing a bunch in bulk.
- Use pypy3 to run `parsedmarc`, as [described in the documentation](https://domainaware.github.io/parsedmarc/#installation-using-pypy3) to speed up processing time

**Comment by mfritts** [comment]
I'm using the --watch option running as a service. We're using an old MailEnable server to catch those reports currently, the IMAP connection is working well except for the timeout and I haven't found a way to change that limit on that mail server. The server running parsedmarc and the mailenable server are running on the same local network. 

I have just updated to the lastest dev release and restarted, I'll see how that goes. I may try the pypy3 method if it's still having trouble keeping up. I may also split some of our client domains to get those reports on a different mailbox on a different system to spread out the load. parsedmarc was working great on the first 10-20 domains that I setup DMARC on, 75 domains maybe is a lot of work to do, maybe too much.

Thanks for your help

**Comment by mfritts** [comment]
Just adding short update, FYI. 
Servers seem to be keeping up better now, had about 200 reports overnight but none waiting to be processed when I checked it this morning. Looks like the update helped. And I didn't make the changes to reduce the load, it just seems to be working better. 

Thanks again.
