### ISSUE TITLE
Remove credentials from CLI

### ISSUE THREAD

**Issue by hvdkooij** [domainaware/parsedmarc#48]
This is a feature request. But is also has security impact. 

Currently the IMAP credentials are used on the commandline.
Which makes them visible in a lot of places. Like log files, status outputs, ......
Is there way to store in a separate file and point to it from the commandline?
That would reduce the exposure.

**Comment by seanthegeek** [comment]
Completed in the 6.0.0 release. Thanks!

https://domainaware.github.io/parsedmarc/#configuration-file
