### ISSUE TITLE
smtp_tls setting for ini file wrong in usage.md and docs

### ISSUE THREAD

**Issue by edwhardo** [domainaware/parsedmarc#486]
What an awesome project!
I noticed the commit for smtp_tls so I moved all of the previously categorized INVALID smtp_tls emails back to the Inbox in hope that they'd be processed.
They were definitely processed and moved in to a new folder, aptly named SMTP_TLS.

I realized nothing would display in grafana because the dashboard hasn't been upgraded, so I tried looking for indexes in elasticsearch and couldn't see any. Then, I had a look in cli.py and noticed that I was missing an entry from the ini file. The following needs to be in the section 
[general]
save_smtp_tls = True

**Comment by edwhardo** [comment]
I closed the issue because I thought it was in the docs, but have now re-opened it because I noticed docs and usage say "save_smtp_sts"
but should be "save_smtp_tls"
The latter is in the code (e.g. cli.py)

**Comment by AnaelMobilia** [comment]
@edwhardo https://github.com/domainaware/parsedmarc/commit/0fa6bebf5a96180ab2e54da7e940507a5ecc6a19 should have resolve your last comment :)

Regards
