### ISSUE TITLE
Review, and if not needed, remove the 'parallel' parameter from everywhere

### ISSUE THREAD

**Issue by Szasza** [domainaware/parsedmarc#490]
Right now the `parallel` parameter is broadly used and passed around the code, but seemingly to no avail. It doens't seem to be used anywhere, not even at it's final upstream, `get_ip_address_info`.

If there is a purpose for it, it would be great to utilise it. Otherwise it may be best to remove it to reduce the code noise.

**Comment by AnaelMobilia** [comment]
Hello @Szasza ,

The parameter was set-up on #62 -> https://github.com/domainaware/parsedmarc/pull/62/files#diff-953601e25cfe2a31ac1b2602fcab0be206d5c7bb860165d66679f455ead64fcf

As you detect, it's no longer used for `get_ip_address_country`... looks like it could be deleted globally :-)
