### ISSUE TITLE
ALREADYEXISTS after 1st run

### ISSUE THREAD

**Issue by cataldoc** [domainaware/parsedmarc#5]
Hi

I'm experiencing this issue after the first run:

ERROR:parsedmarc:IMAP Error: create failed: [ALREADYEXISTS] Mailbox already exists

(using this command: /bin/parsedmarc --watch --silent --delete --output /home/dmarc/www/ -a OLD -H "my_mail_server" -u "my_mailbox" -p "my_password"

Using dovecot 2.2.10 

First manual run completed without errors, from the 2nd one I get the error.

If I change the archive folder with the -a switch it works, but starting from the 2nd run I get the error again.

**Comment by seanthegeek** [comment]
Thy that command without the `--delete` switch. `-a/--archive` and delete are mutually exclusive options. I'll add an error message for that case.

**Comment by seanthegeek** [comment]
Ah, I see the problem. I need ti check f a folder already exists before I create it. I'll fix that

**Comment by seanthegeek** [comment]
Hmmm... the server is complaining that `parsedmarc` trying to create a folder that already exists, [but it checks for that](https://github.com/domainaware/parsedmarc/blob/master/parsedmarc/__init__.py#L1097). 

I'll spin up a local dovecot server and do dome testing.

**Comment by seanthegeek** [comment]
@cataldoc I set up a local dovecot server, and was unable to replicate the issue.

Debian 9 Stretch
dovecot version 2.2.27 (c0f36b0)

devcot configuration options

```
mail_location = maildir:~/Maildir:LAYOUT=fs
```

**Comment by cataldoc** [comment]
Trying to update my dovecot to version 2.3... 

I didn't customize the configuration that much... is almost vanilla (from centos rpm)

**Comment by seanthegeek** [comment]
Don't worry about trying to upgrade the mail server. I think I just pushed work around to git, but I want to make sure before pushing it to PyPI

Try installing the latest build from git

**Comment by cataldoc** [comment]
Doh, too late :) 

I updated dovecot anyway, and also downloaded parsedmarc 3.7.4 from git

The error I get now is different (same error with both the old and the new version of parsedmarc)

# /bin/parsedmarc --delete --output /home/dmarc/www/ -H "my_mail_server" -u "my_email" -p "_my_password_"

ERROR:parsedmarc:IMAP Error: create failed: [CANNOT] Invalid mailbox name: Name must not have '/' characters (0.001 + 0.000 secs)

Attached my dovecot configuration
[doveconf.txt](https://github.com/domainaware/parsedmarc/files/2305906/doveconf.txt)

**Comment by seanthegeek** [comment]
@cataldoc This bug was officially fixed in the 3.8.0 release that I just pushed to PyPI. It contains some other mail processing fixes, so please upgrade as soon as possible.

**Comment by cataldoc** [comment]
Perfect, tnx it works now 👍
