### ISSUE TITLE
Problems with indexes and Kibana dashboard

### ISSUE THREAD

**Issue by LoserFriendly** [domainaware/parsedmarc#52]
Hi there,
sorry for bothering about an issue caused by myself doing dumb operations on the server, but I'm not able to display new data in the dashboard anymore. It's not a bug of parsedmarc, but I don't know where else to ask for help.
Yesterday I updated parsedmarc to version 6.0.0 and I thought it were a good idea to renew the Kibana index patterns as if I were coming from a version prior to 5. So I followed the instructions but, when I tried to import the indexes from the downloaded kibana_saved_objects.json, I got the message you can see in Screenshot_001. After creating 2 new index patterns (dmarc_aggregate* and dmarc_forensic* that matched all the daily indexes of each type) I'm now able to display data until 02/05/2019, but even if 02/06 and 02/07 reports have been parsed (after all the mess), the results are not shown in the dashboard, as you can see in Screenshot_002. Any suggestion, apart starting from scratch with a clean install and paying some more attention? Should you need any further information, please don't hesitate to ask. Thank you very much for any hint you feel to share with me.
![screenshot_001](https://user-images.githubusercontent.com/45626435/52400390-49fdca00-2abf-11e9-898a-d2631c919241.png)
![screenshot_002](https://user-images.githubusercontent.com/45626435/52400391-4a966080-2abf-11e9-9835-e0c930a85dd7.png)

**Comment by seanthegeek** [comment]
When I updated the dashboards last time, I forgot to incluse the index patterns in the export file. Sorry! I just pushed a corrected version of `kibana_saved_objects.json`. Let me know how that works for you.

**Comment by LoserFriendly** [comment]
For some reason (probably me messing things up while trying to get everything working) the new `kibana_saved_objects.json` didn't do the trick. Luckily there was a backup of the working virtual machine made on 02/05 that I could use. I've started over the upgrade to version 6.0.1, imported the correct `kibana_saved_objects.json` (thanks) and now everything seems to work fine.

Thank you for your help and once again for coding this fine software.

**Comment by seanthegeek** [comment]
Glad to hear it! :)
