### ISSUE TITLE
ERROR:utils.py:274:More than one match found for (...

### ISSUE THREAD

**Issue by phr0gz** [domainaware/parsedmarc#56]
Hello, I'm currently testing parsedmarc 6.0.1 :)

I saw some errors in the console but not present in the log_file.

The error is the following:
```
ERROR:utils.py:274:More than one match found for (?:id\s+(?P<id>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+with(?! cipher)|\s+for|\s+via|;)) in from bulk1-smtp.messagingengine.com bulk1-smtp.messagingengine.com 123.123.123.123 ^M
 using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 256/256 bits ^M
 Client did not present a certificate ^M
 by mygateway.mydomain.com MTA with ESMTPS id 43ySkp6wpdz4RFQs^M
 for <abuse@mydomain.com>; Mon, 11 Feb 2019 02:24:50 +0100 CET
```

How bad is it?

**Comment by seanthegeek** [comment]
This is a non-fatal message parsing error. It should still process the report. Did it?

**Comment by phr0gz** [comment]
Thx for the feedback!
It seems to process the report (there are 800 reports to process, hard to say with the imap test mode). I will try to disable the test mode in the imap option to see if something is drop in the Archive/Invalid.

**Comment by seanthegeek** [comment]
Nope. it still counts as valid because it was still able to parse the report :)
