### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by seanthegeek** [domainaware/parsedmarc#573]
Python unit tests have been failing since commit https://github.com/domainaware/parsedmarc/commit/92b12eaacfc707d04bfdfbe637a545e2a6778358 and I'm not sure why. Nothing in that change should affect the tests, and the tests pass on my local system.

**Comment by nhairs** [comment]
I didn't check but I think the XML parsing library changed how it parses certain fields.

No matter the cause, the fix is key straightforward see PR associated with: https://github.com/nhairs/parsedmarc-fork/issues/41

**Comment by seanthegeek** [comment]
@nhairs Nope. It turned out to be a regression in `mail-parser`. I have released a new version of `mailsuite` that pins `mail-parser` to the previous version and required that version in the current `parsedmarc release`.

https://github.com/domainaware/parsedmarc/blob/master/CHANGELOG.md#8152

https://github.com/SpamScope/mail-parser/issues/123

**Comment by nhairs** [comment]
Huh weird, it looks like there were different errors in different pipeline. For reference this was the one I was looking at.

https://github.com/domainaware/parsedmarc/actions/runs/11280688896/job/31374215738#step:8:305
