### ISSUE TITLE
Mistyped the version number

### ISSUE THREAD

**Issue by dwydler** [domainaware/parsedmarc#577]
Hi Sean,
You made a typo in the version number in the last release.
![image](https://github.com/user-attachments/assets/f762f8c4-ad30-4d42-a57b-685c3c282bff)

I think that should be called 8.16.0?

**Comment by drupol** [comment]
As a Nix maintainer, I'm also curious to know more on this.

**Comment by seanthegeek** [comment]
Crap. fixed.
