### ISSUE TITLE
dmarc_aggregate not creating

### ISSUE THREAD

**Issue by arunvasan-r** [domainaware/parsedmarc#58]
Dear Sir,
I have update to the version 6.0.2 after that elastic search dmarc_aggregate index is not creating. It moves successfully to the aggregate folder of mail server with out creating the dmarc_aggregate. This issue happen after the update of 6.0.2. Then I have updated to the latest 6.0.3. After update I have moved one mail from Aggregate folder to Inbox for processing. Now showing debug information as invalid and move the message to invalid folder of mail server now.
Kindly inform what debug file information I have to sent for this.
Regards,
R.Arun Vasan

**Comment by seanthegeek** [comment]
Fixed in 6.1.0

**Comment by arunvasan-r** [comment]
Dear Sir,
Thanks for the release. Now working perfect.
Regards,
R.Arun Vasan
