### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by xennn** [domainaware/parsedmarc#66]
Hello,

i have a Problem since a update from parsedmarc.
I see now you add a configuration file for the connection. But now i get a error if i try to connect.
Befor the update it work.

0it [00:00, ?it/s]
   DEBUG:__init__.py:928:Connecting to IMAP over plain text
   ERROR:cli.py:463:IMAP Error: socket error: EOF

Config File:

# This is an example comment

[general]
save_aggregate = True
save_forensic = True
nameservers = 10.2.1.105

[imap]
host = servername
user = dmarcreports@domain.de
password = password
watch = True
ssl = false
delete = true

Whats wrong here?

**Comment by xennn** [comment]
you can close this. My issue sorry

**Comment by seanthegeek** [comment]
No worries.

**Comment by spryffee** [comment]
@xennn I have the same issue. What was the problem?

**Comment by xennn** [comment]
https://github.com/domainaware/parsedmarc/issues/70#issuecomment-485709671

Use internal dns server
