### ISSUE TITLE
DMARC Summary - kibana error - responseAggs is undefined

### ISSUE THREAD

**Issue by Ooviov1r** [domainaware/parsedmarc#68]
imported the kibana_saved_objects.json
Dashboard DMARC Summary gives the error responseAggs is undefined

**Comment by seanthegeek** [comment]
Can you provide the full error output? It looks like this might be related to

https://github.com/elastic/kibana/issues/22390

**Comment by seanthegeek** [comment]
Based on emails with the user, this error message was caused by empty data in Elastecsearch, due to the user typoing the config setting `hosts` as `host`.

Added a critical error message when required settings are missing in 6.3.0.
