### ISSUE TITLE
Failing on invalid squished XML

### ISSUE THREAD

**Issue by rfrovarp** [domainaware/parsedmarc#69]
I'm getting failure to parse some of the reports due to them not being a valid aggregate report. From the little bit of testing I've done on 6.2.2 is that these reporters aren't sticking a newline after the XML header. So you end up with one line with the header.

So something like...

<?xml version="1.0" encoding="utf-8"?><feedback><report_metadata><org_name>...

If I insert a newline after the XML header it works. Don't know if there is a way to inject a newline automatically so parsing from IMAP works for those reports.

**Comment by seanthegeek** [comment]
I've seen similar issues with other reporters (they misspell a XML tag). I've thought about writing in workarounds for these kinds of errors, but have decided against it for a few reasons:

- parsedmarc should act as a DMARC report validator
- It's difficult to cover every possible syntax error 
- Reporters sending invalid reports are typically low volume

Happy o get your thoughts though?

**Comment by rfrovarp** [comment]
I'm not a Python dev, so I'm not sure how the XML parser there works.

https://github.com/domainaware/parsedmarc/blob/2f44d8fe3d59e16a858005d67eea72870bed4b29/parsedmarc/__init__.py#L52

That matches to the end of the line, at least due to the ".*". Not entirely sure how the multiline part works with the sub method. But if it were "^<\?xml .*?>$" that would more accurately match an actual XML header string. But with the reports missing a newline after the header and the existing regex, it is grabbing the XML document in addition to the header. 

https://github.com/domainaware/parsedmarc/blob/2f44d8fe3d59e16a858005d67eea72870bed4b29/parsedmarc/__init__.py#L234

But the only thing that is done with the header is to remove it as sometimes they are invalid according to the comment. Then it gets flung into the Python parser. The schema replacement tries to put a header back in, without a newline on 237. So either that doesn't work, or the Python parser doesn't care about a header without a newline. So from my reading, if the files were left alone, they would probably work as valid.

**Comment by seanthegeek** [comment]
Gotcha. Fixed in the 6.3.0 release. :)
