### ISSUE TITLE
Option to move invalid reports

### ISSUE THREAD

**Issue by mikesiegel** [domainaware/parsedmarc#7]
Awesome project! One issue I've run into: invalid DMARC reports are left where they are.  On subsequent runs, it will again attempt to parse them.

I think an additional folder in Archive (say 'Invalid') would be a good option for people who don't want to delete, but rather move them somewhere.

**Comment by seanthegeek** [comment]
Good point. I'll add this after I get back from vacation next week.

**Comment by seanthegeek** [comment]
@mikesiegel This is implemented in 1.8.2, along with your nameserver bug fix (I fixed a syntax error in that btw)
