### ISSUE TITLE
Array of SSL errors

### ISSUE THREAD

**Issue by fraserc182** [domainaware/parsedmarc#70]
This may be my issue, but hoping I can be pointed in the correct direction if it is.

The parsedmarc.ini file is as simple as it can be.

When running  parsedmarc -c /etc/parsedmarc.ini
I get one of three issues:

1. 0it [00:00, ?it/s]
   ERROR:cli.py:546:IMAP Error: SSL error: EOF occurred in violation of protocol (_ssl.c:600)

2. 0it [00:00, ?it/s]
   ERROR:cli.py:546:IMAP Error: SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

3. The command appears to run and hang. When I cancel, I get the following traceback.

0it [00:00, ?it/s]
^CTraceback (most recent call last):
  File "/usr/bin/parsedmarc", line 11, in <module>
    load_entry_point('parsedmarc==6.3.1', 'console_scripts', 'parsedmarc')()
  File "/usr/lib/python3.4/site-packages/parsedmarc/cli.py", line 539, in _main
    strip_attachment_payloads=sa
  File "/usr/lib/python3.4/site-packages/parsedmarc/__init__.py", line 1048, in get_dmarc_reports_from_inbox
    strip_attachment_payloads=sa)
  File "/usr/lib/python3.4/site-packages/parsedmarc/__init__.py", line 744, in parse_report_email
    parallel=parallel)
  File "/usr/lib/python3.4/site-packages/parsedmarc/__init__.py", line 406, in parse_aggregate_report_file
    parallel=parallel)
  File "/usr/lib/python3.4/site-packages/parsedmarc/__init__.py", line 313, in parse_aggregate_report_xml
    parallel=parallel)
  File "/usr/lib/python3.4/site-packages/parsedmarc/__init__.py", line 111, in _parse_report_record
    parallel=parallel)
  File "/usr/lib/python3.4/site-packages/parsedmarc/utils.py", line 362, in get_ip_address_info
    timeout=timeout)
  File "/usr/lib/python3.4/site-packages/parsedmarc/utils.py", line 187, in get_reverse_dns
    timeout=timeout)[0]
  File "/usr/lib/python3.4/site-packages/parsedmarc/utils.py", line 161, in query_dns
    resolver.query(domain, record_type, tcp=True)))
  File "/usr/lib/python3.4/site-packages/dns/resolver.py", line 908, in query
    source_port=source_port)
  File "/usr/lib/python3.4/site-packages/dns/query.py", line 489, in tcp
    send_tcp(s, wire, expiration)
  File "/usr/lib/python3.4/site-packages/dns/query.py", line 388, in send_tcp
    _wait_for_writable(sock, expiration)
  File "/usr/lib/python3.4/site-packages/dns/query.py", line 160, in _wait_for_writable
    _wait_for(s, False, True, True, expiration)
  File "/usr/lib/python3.4/site-packages/dns/query.py", line 131, in _wait_for
    if not _polling_backend(fd, readable, writable, error, timeout):
  File "/usr/lib/python3.4/site-packages/dns/query.py", line 90, in _poll_for
    event_list = pollable.poll(long(timeout * 1000))
KeyboardInterrupt

**Comment by seanthegeek** [comment]
This is a server side problem. It looks similar to what @xennn reported in issue #66. That ended up being a server side issue, but I don't know what the exact problem was, or how it was fixed.  @xennn, can you provide details?

**Comment by xennn** [comment]
Sure. I fix this with this:

[general]
save_aggregate = True
save_forensic = True
nameservers = 1.1.1.1
 
[imap]
host = Servername
user = user@domain.de
port = 143
password = PASSWORT
watch = False
ssl = False
delete = True
reports_folder = INBOX
 
[elasticsearch]
hosts = 127.0.0.1:9200
ssl = False

**Comment by fraserc182** [comment]
Hi, thanks for getting back to me. Let me try this and let you know the outcome @xennn thanks for letting me know what you did to fix the issue!

**Comment by fraserc182** [comment]
Just to update on this, I ran the command with the --debug flag and get this output:

parsedmarc -c /etc/parsedmarc.ini --debug
0it [00:00, ?it/s]
   DEBUG:__init__.py:928:Connecting to IMAP over plain text
   DEBUG:__init__.py:851:IMAP server supports: ['IMAP4', 'IMAP4REV1', 'AUTH=PLAIN', 'AUTH=NTLM', 'AUTH=GSSAPI', 'UIDPLUS', 'MOVE', 'ID', 'XPROXY3', 'CHILDREN', 'IDLE', 'NAMESPACE', 'LITERAL+']
   DEBUG:__init__.py:999:Found 7149 messages in IMAP folder INBOX
   DEBUG:__init__.py:1005:Processing message 1 of 7149: UID 405


It does appear to be able to connect to the mailbox, then it just freezes after that. 7149 messages isn't too many is it?

**Comment by fraserc182** [comment]
A new error! 

Looks like it can actually do something now, I had to point the nameservers towards our internal ones.

parsedmarc -c /etc/parsedmarc.ini --debug
0it [00:00, ?it/s]
   DEBUG:__init__.py:928:Connecting to IMAP over plain text
   DEBUG:__init__.py:851:IMAP server supports: ['IMAP4', 'IMAP4REV1', 'AUTH=PLAIN', 'AUTH=NTLM', 'AUTH=GSSAPI', 'UIDPLUS', 'MOVE', 'ID', 'XPROXY3', 'CHILDREN', 'IDLE', 'NAMESPACE', 'LITERAL+']
   DEBUG:__init__.py:999:Found 7 messages in IMAP folder TEST
   DEBUG:__init__.py:1005:Processing message 1 of 7: UID 1
   DEBUG:__init__.py:1005:Processing message 2 of 7: UID 2
   DEBUG:__init__.py:1005:Processing message 3 of 7: UID 3
   DEBUG:__init__.py:1005:Processing message 4 of 7: UID 4
   DEBUG:__init__.py:1005:Processing message 5 of 7: UID 5
   DEBUG:__init__.py:1005:Processing message 6 of 7: UID 6
   DEBUG:__init__.py:1005:Processing message 7 of 7: UID 7
   DEBUG:__init__.py:1113:Moving aggregate report messages from TEST to TEST
   DEBUG:__init__.py:1119:Moving message 1 of 7: UID 1
   DEBUG:__init__.py:957:Moving message UID(s) 1 to Archive/Aggregate
   ERROR:__init__.py:1128:IMAP error: Error moving message UID 1: command: UID => unexpected response: 'b'[COPYUID 62 1 1]
   DEBUG:__init__.py:1119:Moving message 2 of 7: UID 2
   DEBUG:__init__.py:957:Moving message UID(s) 2 to Archive/Aggregate
   ERROR:__init__.py:1128:IMAP error: Error moving message UID 2: command: UID => unexpected response: 'b'[COPYUID 62 2 2]
   DEBUG:__init__.py:1119:Moving message 3 of 7: UID 3
   DEBUG:__init__.py:957:Moving message UID(s) 3 to Archive/Aggregate
   ERROR:__init__.py:1128:IMAP error: Error moving message UID 3: command: UID => unexpected response: 'b'[COPYUID 62 3 3]
   DEBUG:__init__.py:1119:Moving message 4 of 7: UID 4
   DEBUG:__init__.py:957:Moving message UID(s) 4 to Archive/Aggregate
   ERROR:__init__.py:1128:IMAP error: Error moving message UID 4: command: UID => unexpected response: 'b'[COPYUID 62 4 4]
   DEBUG:__init__.py:1119:Moving message 5 of 7: UID 5
   DEBUG:__init__.py:957:Moving message UID(s) 5 to Archive/Aggregate
   ERROR:__init__.py:1128:IMAP error: Error moving message UID 5: command: UID => unexpected response: 'b'[COPYUID 62 5 5]
   DEBUG:__init__.py:1119:Moving message 6 of 7: UID 6
   DEBUG:__init__.py:957:Moving message UID(s) 6 to Archive/Aggregate
   ERROR:__init__.py:1128:IMAP error: Error moving message UID 6: command: UID => unexpected response: 'b'[COPYUID 62 6 6]
   DEBUG:__init__.py:1119:Moving message 7 of 7: UID 7
   DEBUG:__init__.py:957:Moving message UID(s) 7 to Archive/Aggregate
   ERROR:__init__.py:1128:IMAP error: Error moving message UID 7: command: UID => unexpected response: 'b'[COPYUID 62 7 7]
   DEBUG:__init__.py:928:Connecting to IMAP over plain text
   ERROR:cli.py:546:IMAP Error: socket error: EOF

**Comment by seanthegeek** [comment]
Hmm. What mail server software are you running? I have an idea for a workaround for you to try soon.

**Comment by fraserc182** [comment]
We are running Exchange 2013 currently.

**Comment by xennn** [comment]
I think it is this:
https://support.microsoft.com/en-us/help/3064393/bad-command-12-error-occurs-and-imap-capability-commands-are-not-offer

**Comment by fraserc182** [comment]
@xennn that appears to relate to exchange 2010, we are on 2013.
"Cause
This issue occurs because Exchange Server 2010 does not support IMAP capability for ID and MOVE commands that are supported in Exchange Server 2013."

**Comment by seanthegeek** [comment]
@fraserc182 Please ensure your Exchange 2013 servers are patched with the latest cumulative update https://support.microsoft.com/en-us/help/4099855/cumulative-update-21-for-exchange-server-2013

**Comment by fraserc182** [comment]
Thanks, I will look into this and apply the patch if required.

**Comment by fraserc182** [comment]
Hi, I have checked with our exchange admins and the above patch is applied.
So as to what could be the problem here I am unsure.

**Comment by seanthegeek** [comment]
I'm not sure what the cause is either, but I think I have a workaround. Please upgrade to 6.3.6, which will try to manually copy and delete the email if `MOVE` fails.

**Comment by fraserc182** [comment]
Perfect, I will update and let you know how I get on. 
Thanks for your help on this.

**Comment by seanthegeek** [comment]
@fraserc182 Have you had a chance to test this?

**Comment by fraserc182** [comment]
Yup, it appears to be working now. 
I am getting ssl errors, but these are more related to the servers own certificates rather than any issues with parsedmarc. 
Thanks for your help!
