### ISSUE TITLE
Elasticsearch Indexes not being created

### ISSUE THREAD

**Issue by twispt** [domainaware/parsedmarc#74]
Version 6.3.3 is silently failing to create Elasticsearch indexes.  Rolling back to 6.3.2 resolves the issue. Index suffix has no effect on the behavior either way.

`DEBUG:elastic.py:285:Saving aggregate report to Elasticsearch
DEBUG:elastic.py:210:Creating Elasticsearch index: dmarc_aggregate_dss-2019-04
ERROR:cli.py:91:Elasticsearch Error: Elasticsearch error: 'dict' object has no attribute 'indices'`

**Comment by seanthegeek** [comment]
Sorry about that! Fixed in 6.3.4.

**Comment by twispt** [comment]
NP at all. And wow, quick! Appreciate it!
