### ISSUE TITLE
Unknown Delivery-Result "smg-policy-action" in example

### ISSUE THREAD

**Issue by thafreeman** [domainaware/parsedmarc#76]
The example has a "Delivery-Result" header with value "smg-policy-action". But the referred to RFC (http://tools.ietf.org/html/rfc6591) only allows "delivered", "spam", "policy", "reject" and "other". Where did this value come from?

**Comment by seanthegeek** [comment]
I never noticed that. Good catch! Some gateways will violate the RFC and add their own delivery-result values with various meanings specific to that gateway/vendor. Pretty annoying. I'll fix the example. Thanks!

**Comment by thafreeman** [comment]
We process a lot of DMARC forensic and aggregated reports at [URIports](https://www.uriports.com) and most reports follow RFC rules. A large portion of those that fail have the exact same "smg-policy-action" value. The only search results on "smg-policy-action" lead to parsedmarc. I'm unable to find a specification of "smg-policy-action" anywhere on the web. Maybe system administrators just started copying your example data for some odd reason.

**Comment by seanthegeek** [comment]
Aha! It just occurred to me: SMG == "Symantec Messaging Gateway".  It's letting you know an action was taken due to a local policy on the gateway. I which Symantec would follow the RFC and just say `policy`.

I'll leave the example as is then, since it's the only public forensic sample I have (from a third party). That way the sample and the output still match.

**Comment by thafreeman** [comment]
Ahha, thanks for clearing that up. We will convert the value to "policy" then. Although I do not understand why you would "support" violation of RFC. If you want I can help you out with a RFC compliant forensic report.

**Comment by seanthegeek** [comment]
True. I was thinking about that too as soon as I wrote that comment, so I just added some code to normalize that field.

Having a RFC compliant forensic report would be great. Thanks!

**Comment by thafreeman** [comment]
As soon as I receive one for one of my own domains I'll send it to you anonymized.
