### ISSUE TITLE
New example RFC6591 compliant DMARC Forensic report

### ISSUE THREAD

**Issue by thafreeman** [domainaware/parsedmarc#77]
As promised. A new anonymized forensic report. The origin is LinkedIn and contains both "message/feedback-report" and "Content-Type: message/rfc822" with original message headers, "text/plain" and "text/html" message body.

[dmarc_ruf_report_linkedin_eml.txt](https://github.com/domainaware/parsedmarc/files/3130235/dmarc_ruf_report_linkedin_eml.txt)

A reference to [URIports](https://www.uriports.com) would be greatly appreciated.

**Comment by seanthegeek** [comment]
I added it to the samples directory, with credit in the changelog. Thanks!
