### ISSUE TITLE
Add configuration file options for Elasticsearch number_of_shards and number_of_replicas

### ISSUE THREAD

**Issue by Vico999** [domainaware/parsedmarc#78]
Thanks for this great software, and all the hard work you have put into it.
We use [Elasticsearch index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html). This [part of the code](https://github.com/domainaware/parsedmarc/blob/34e428f1cfde7e882e735f1646e78b958240a12c/parsedmarc/elastic.py#L211) overwrites the template.
How can I override/set my own `number_of_shards` and `number_of_replicas`?

**Comment by seanthegeek** [comment]
I just released parsedmarc  6.4.0

> Add `number_of_shards` and `number_of_replicas` as possible options
in the `elasticsearch` configuration file section

**Comment by Vico999** [comment]
Thank you for implementing this feature. I've been using `number_of_replicas` setting since parsedmarc 6.4.0 release. Every month a new index would be created, but `number_of_replicas` setting was not being applied. Looking at the code, `number_of_replicas` will only work if `number_of_shards` is set ([cli.py)](https://github.com/domainaware/parsedmarc/blob/cb63c55b944a78c3b2b0a3e579000dbd44af6025/parsedmarc/cli.py#L325)?
Since I am using the default `number_of_shards` setting (1), I didn't think it was necessary to put `number_of_shards` in the config.
I think the documentation should note that `number_of_shards` must be set if `number_of_replicas` setting is used (i.e no longer 'default').
