### ISSUE TITLE
IMAP error moving message

### ISSUE THREAD

**Issue by quickwick** [domainaware/parsedmarc#80]
Another issue I figured I should mention. I'm only seeing this because I have debug mode on, due to my other issue. After processing e-mails in an IMAP folder, I get an error like this for every single message:
`DEBUG:__init__.py:975:IMAP error: Error moving message UID 86: command: UID => unexpected response: b'[COPYUID 52 86 1146]`

To be clear, the messages are actually being moved successfully, to subfolders under Archive folder.

Exchange 2013 CU 22

**Comment by seanthegeek** [comment]
You are seeing this error in the DEBUG output because that version of Exchange doesn't respond to the MOVE command properly, so parsedmarc falls back to copying and deleting the message instead.
