### ISSUE TITLE
Cannot add data to indexes created in Elasticsearch 6.x after upgrade to Elasticsearch 7.x

### ISSUE THREAD

**Issue by bhozar** [domainaware/parsedmarc#81]
we've recently updating our system to ElasticSearch 7.x and I've noticed an error in syslog:

May 17 06:52:11 _servername_ parsedmarc[11164]:    ERROR:cli.py:96:Elasticsearch Error: Elasticsearch error: RequestError(400, 'illegal_argument_exception',
 'Rejecting mapping update to [dmarc_aggregate-2019-05-16] as the final mapping would have more than 1 type: [_doc, doc]')

This may not be related to ES 7.x, but I only looked for error after the upgrade.

**Comment by bhozar** [comment]
I can confirm this does seem to cause an issue with ParseDMARC when used with ES 7.x. No reports imported, which I assume is due to the above error message.

**Comment by seanthegeek** [comment]
This issue only occurs when trying to add data to DMARC indexes that were created before the upgrade to Elasticsearch 7.0. Creating new indexes works fine. I realize deleting indexes isn't the best workaround, so I'll keep looking for a better solution.

**Comment by seanthegeek** [comment]
I'm honestly not sure how to fix this one. By now those old indexes will be out-of-date. IF anyone really needs them and has a fix, let me know.

**Comment by BananaWanted** [comment]
I just encountered exactly the same error. I'm using a fresh install. That's saying, creating new indexes doesn't work either.

The default `_doc_type` is harded coded as `doc`, in `elasticsearch-dsl`, which is invalid in elasticsearch 7.
https://github.com/elastic/elasticsearch-dsl-py/blob/6.4.0/elasticsearch_dsl/index.py#L9

I've workaround it by upgrade the elasticsearch library: https://github.com/domainaware/parsedmarc/compare/master...BananaWanted:master
