### ISSUE TITLE
IMAP Error: LIST failed: Folder not found

### ISSUE THREAD

**Issue by bluadall** [domainaware/parsedmarc#83]
Hi,

**my problem**:
[root@applslelk002 davmail]# parsedmarc -c /etc/parsedmarc.ini
0it [00:00, ?it/s]
   DEBUG:__init__.py:937:Connecting to IMAP over plain text
   DEBUG:__init__.py:860:IMAP server supports: ['IMAP4REV1', 'AUTH=LOGIN', 'IDLE', 'MOVE', 'SPECIAL-USE']
   ERROR:cli.py:565:IMAP Error: LIST failed: Folder not found

**My parsedmarc.ini**
[general]
save_aggregate = True
save_forensic = True
debug = True
log_file = /var/log/parsedmarc.log

[imap]
host = 172.26.25.104
port = 1143
user = xxxxxx
password = xxxxx
reports_folder = /Proofpoint/dmarc
archive_folder = /Proofpoint/archiv
ssl = False
watch = True

[elasticsearch]
hosts = xxxx:9200
ssl = False

The access via thunderbird from my windows 10 workstation works very well.
Exchange is 2016 with CU11 and EWS. parsedmarc is 6.4.1
Any idea?

**Comment by seanthegeek** [comment]
remove the starting / in your paths
