### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by GurBal** [domainaware/parsedmarc#85]
Hi There, 

I am new to this, looking some help to get this setup. I installed parsedmarc using pip install parsedmarc command. It looks like it's installed properly. 

But when i try to try to run it on CLI i.e. parsedmarc file_path "****", it gives the following error attached
![ParseDMARC](https://user-images.githubusercontent.com/51963664/59698456-f6a63180-91ac-11e9-805f-85282f47da23.png)

Coud you please provide guidance how to fix this?

Thanks

**Comment by seanthegeek** [comment]
Use Python 3 pip3

```sudo apt-get install python3-pip
sudo -H pip uninstall parsedmarc
sudo -H pip3 install -U paparsedmarc
```
