### ISSUE TITLE
Warning when running parsedmarc

### ISSUE THREAD

**Issue by GurBal** [domainaware/parsedmarc#87]
Hi There,

When i try to run parsedmarc, it parses the file appropriately but i see the following warning errors in the beginning.

![image](https://user-images.githubusercontent.com/51963664/59795602-d81d6480-9298-11e9-9897-c474feca482e.png)

Would this cause any potential issues?

Thanks,

**Comment by seanthegeek** [comment]
Hi. this means that you are missing the GeoIP database, so you won't get GeoIP information

To fix this, install the `geoipupdate` utility, which will regularly download a fresh copy for you.

```
sudo apt-get install geoipupdate -y 
```
