### ISSUE TITLE
Alternatives to IMAP

### ISSUE THREAD

**Issue by mda1125** [domainaware/parsedmarc#88]
I'd like to be able to configure an option to pull reports from a file location vs IMAP.  We've currently disabled IMAP for all users in order to use Mobile Device Management.  In doing so, IMAP isn't really an option.

Is there any other method to save the reports to and have them picked up?

In the meantime, I could take each report and just manually upload it.

**Comment by seanthegeek** [comment]
Hi you could copy all of the emails to a directory and run this command in that directory.

```
parsedmarc -c /etc/parsedmarc.ini *
```

Also, check with your mail provider to see if you can enable IMAP for just the DMARC mailbox, or IP whitelist.
