### ISSUE TITLE
Parse an Individual Report

### ISSUE THREAD

**Issue by mda1125** [domainaware/parsedmarc#89]
Assuming the email import option isn't working at the moment .. how do you manually get the XML file or .GZ file into Kibana as it allows you to upload a JSON object.

Maybe there is a way to SSH into the box and put some XML or .GZ files into a folder and have the service parse and import them?

**Comment by michaeldavie** [comment]
I have a similar requirement. I already have the reports in XML files, and I would like to flatten them into CSV.

**Comment by DataSquid** [comment]
Same.  I have 140k rua attachments already pulled from emails and I just need to import them.

**Comment by seanthegeek** [comment]
You can already do this.

Create a parsedmarc config file with just the elasticsearch config part (or Splunk) without the IMAP part, cd to the directory containing the report xml, zip, gzip, or even eml or msg files, and run

```
parsedmarc -c /etc/parsedmarc.ini *
```

**Comment by DataSquid** [comment]
> @mda1125, @DataSquid
> 
> You can already do this.
> 
> Create a parsedmarc config file with just the elasticsearch config part (or Splunk) without the IMAP part, cd to the directory containing the report xml, zip, gzip, or even eml or msg files, and run
> 
> ```
> parsedmarc -c /etc/parsedmarc.ini *
> ```
> 

Alas, when you do this with a directory containing >140k files, 
```
bash: /usr/local/bin/parsedmarc: Argument list too long
```
is the result.

**Comment by seanthegeek** [comment]
Hmm. I didn't know argparse had a limit to the number of arguments. 

This probably isn't the most efficient workaround, but try using `xargs`. This will run `parsedmarc` separately on each file in the directory  

```
ls *.xml *.zip *.gz *.eml *.msg | xargs -I {} parsedmarc -c /etc/parsedmarc.ini {}
```

**Comment by DataSquid** [comment]
ls has similar constraints.  The following seems to be working through my local backlog now:

```
ls | xargs -I {} parsedmarc -c /etc/parsedmarc.ini {}
```

Thanks.

**Comment by mda1125** [comment]
Saved attachments from 20 reports
Put attachments in directory
cd to the directory
parsedmarc -c /etc/parsedmarc.ini *

Dashboard is empty...

sudo nano /etc/parsedmarc.ini

Put the following lines in the file. Replace the palceholders as necessary.

[general]
# Save aggregate and forensic reports to Elasticsearch
save_aggregate = True
save_forensic = True

[elasticsearch]
# Send data to Elastichsearch, which listens on port 9200.
hosts = 127.0.0.1:9200
ssl = False

**Comment by seanthegeek** [comment]
@mda1125 If they are old reports, you may need to adjust the time window at the top of the dashboard, The default view only shows report data from the last 7 days.
