### ISSUE TITLE
IMAP Error

### ISSUE THREAD

**Issue by WinstonAcid** [domainaware/parsedmarc#9]
Hello,

recieved the folling error on Exchange 2010: `ERROR:parsedmarc:IMAP Error: UID command error: BAD [b'Command Error. 12']`
i think its because of IMAP command MOVE [https://support.microsoft.com/de-de/help/3064393/bad-command-12-error-occurs-and-imap-capability-commands-are-not-offer](url)
only solution is to run parsedmarc with --test or -d

is there a better solution?

**Comment by JayBuckley7** [comment]
It's really messy but this is what i have done:


if parsed_email["report_type"] == "aggregate":
                    print("saving aggregate to elastic")
                    elastic.save_aggregate_report_to_elasticsearch(parsed_email["report"])
                    server.copy(message_uid, aggregate_reports_folder)
                    server.add_flags(message_uid, [imapclient.DELETED])
                    server.expunge()   
                elif parsed_email["report_type"] == "forensic":
                    print("saving forensic to elsatic")
                    forensic_reports.append(parsed_email["report"])
                    elastic.save_forensic_report_to_elasticsearch((parsed_email["report"]))
                    server.copy(message_uid, forensic_reports_folder) 
                    server.add_flags(message_uid, [imapclient.DELETED])
                    server.expunge()

**Comment by seanthegeek** [comment]
I just uploaded a new version that will use they copy and delete method if the IMAP server does not support `MOVE`.
