### ISSUE TITLE
Add an offline option

### ISSUE THREAD

**Issue by michaeldavie** [domainaware/parsedmarc#90]
I would like to have the option to do analysis offline, i.e. without reaching out to the internet to enrich the data with reverse DNS or geo IP information.

**Comment by seanthegeek** [comment]
An `--offline` CLI option and config file option (under the general section) have been added in parsedmarc 6.5, which has just been released.

**Comment by michaeldavie** [comment]
Thanks! I've been using a stripped-down version of the library for my project, and it's been a godsend. Keep up the good work!

**Comment by seanthegeek** [comment]
I forgot to mention, it will still try to use a local GeoIP2-country file if you have one, so it can to geolocation even offline.

I also finally split out all of the email I/O into a new package called [`mailsuite`](https://seanthegeek.github.io/mailsuite/) To make working with mailboxes super easy for other projects. :)
