### ISSUE TITLE
No Source Countries

### ISSUE THREAD

**Issue by mda1125** [domainaware/parsedmarc#92]
I have run the command sudo apt install python3-pip geoipupdate and there are no errors.

I can run geoiplookup without issues.

But the reports never seem to show any country data but it shows all other data.

During manual imports I see this error in the logs:
WARNING:utils.py:279:Cannot download GeoIP database in parallel mode

And utils.py points to a URL that I don't think exists
https://geolite.maxmind.com/download/geoip/database

If you go to this address it immediately redirects to
https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by seanthegeek** [comment]
Try running

sudo geoipupdate

to download the latest GeoIP database in the correct location.

Then delete the elasticsearch indexes and re-run parsedmarc

**Comment by mda1125** [comment]
sudo geoipupdate ran no errors.

I can delete the Index from the Kibana dashboard correct?

Then just re-run parsedmarc in the directory with the reports?

**Comment by seanthegeek** [comment]
Yep. You can delete the Elasticsearch indexes by clicking on the management application item in Kibana, and then clicking on index management under Elasticsearch.

**Comment by mda1125** [comment]
Just did... 
Re-ran parsedmarc -c /etc/parsedmarc.ini * in the directory where the reports are

I saw it have a progress bar and finish which did not happen before.

I'm waiting to see if the Index is rebuilt and shows up.  So far... nothing.  I assume it takes a few.

**Comment by seanthegeek** [comment]
Has parsedmarc exited yet? It should create the indexes and save the results just before it exits.

**Comment by mda1125** [comment]
parsedmarc -c /etc/parsedmarc.ini *
 96%|█████████████████████████████████████████▏ | 22/23 [00:04<00:00,  1.97it/s]
ubuntu@ParseDMARC:~/dmarc-reports$

**Comment by seanthegeek** [comment]
Odd. Try running the command with --debug

**Comment by mda1125** [comment]
LOL.. just did that.

parsedmarc -c /etc/parsedmarc.ini * --debug
 96%|██████████████████████████████████████████████████████████▎  | 22/23 [00:04<00:00,  6.06it/s]
ubuntu@ParseDMARC:~/dmarc-reports$

**Comment by seanthegeek** [comment]
This is really weird. I'm wondering what library is generating the progress bar, because that's not normal. You're also not getting any debug messages like you should. I'm about to go to bed (I'm in the eastern US). I'll look into this more tomorrow.

Do you happen to have 23 files in that directory?

**Comment by mda1125** [comment]
I have 13 now.. I remove a few that somebody else uploaded.

parsedmarc -c /etc/parsedmarc.ini * --debug
 77%|██████████████████████████████████████████████▉              | 10/13 [00:03<00:00,  4.65it/s]
ubuntu@ParseDMARC:~/dmarc-reports$

**Comment by seanthegeek** [comment]
It looks like it's crashing on report 10 or 13 for some reason, which would explain why it doesn't get to the Elasticsearch part. Would you mind sending me a copy of those reports so I can do some debugging?

whalenster@gmail.com

**Comment by seanthegeek** [comment]
I did more digging, and it turns out there is some sort of race condition that fails to update the progress bar, but all reports are being processed.

Please make sure you have the elasticsearch section correct in your config file.

I also released parsedmarc 6.5m which has faster DNS queries.
