### ISSUE TITLE
Fresh Install No Index

### ISSUE THREAD

**Issue by mda1125** [domainaware/parsedmarc#93]
I did a fresh install onto Ubuntu 18.04 following this blog post which seemed to work the last time.

https://www.linuxbabe.com/mail-server/parsedmarc-ubuntu-18-04-16-04

I upload a few zipped aggregate reports.

Run parsedmarc -c /etc/parsedmarc.ini *

Get a lot of WARNING:utils.py:279:Cannot download GeoIP database in parallel mode

Fine.. 

But in the end, no Index is created so none of the dashboards pull in data.

**Comment by mda1125** [comment]
sudo geoipupdate

ubuntu@ip-10-47-128-245:~$ parsedmarc -c /etc/parsedmarc.ini * --debug
 92%|███████████████████████████████████████▍   | 11/12 [00:03<00:00,  3.74it/s]
ubuntu@ip-10-47-128-245:~$

It's like no matter how many files or how few files I have in the folder, it doesn't finish and no Index is created.  Odd because I got it to work the other day.  But today, fresh install.. just doesn't quite finish.

--debug doesn't report anything.

**Comment by seanthegeek** [comment]
hmmm. I can't duplicate this. If you run parsedmarc * without any config file or other options, what do you get?

**Comment by mda1125** [comment]
If I run it as parsedmarc * without any other options ...

It seems to progress thru any XML files it can and displays a big uncompressed list.

Then finishes.

I go back to Kirana and under Management -- Index Management

Nothing is there.

Running a check on the status of Parsemarc as a service I get this

ubuntu@ip-10-47-128-166:~$ systemctl status parsedmarc
● parsedmarc.service - parsedmarc watcher
   Loaded: loaded (/etc/systemd/system/parsedmarc.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-06-28 15:16:41 UTC; 2s ago
     Docs: https://domainaware.github.io/parsedmarc/
  Process: 10666 ExecStart=/usr/local/bin/parsedmarc -c /etc/parsedmarc.ini (code=exited, status=1/FAILURE)
 Main PID: 10666 (code=exited, status=1/FAILURE)

Jun 28 15:16:41 ip-10-47-128-166 systemd[1]: parsedmarc.service: Main process exited, code=exited, status=1/FAILURE
Jun 28 15:16:41 ip-10-47-128-166 systemd[1]: parsedmarc.service: Failed with result 'exit-code'.

Makes me think that the import is working but the service isn't listening to import that data into Elastic Search?

sudo nano /etc/parsedmarc.ini

[general]
# Save aggregate and forensic reports to Elasticsearch
save_aggregate = True
save_forensic = True

[elasticsearch]
# Send data to Elastichsearch, which listens on port 9200.
hosts = 127.0.0.1:9200
ssl = False

**Comment by GurBal** [comment]
Could you check elasticsearch logs and check if you see any errors there? 

I had similar issue and i had to look into elasticsearch logs and figure out i had some issues with elasticsearch setup.

**Comment by mda1125** [comment]
ubuntu@ip-10-47-128-166:~$ cd /var/log/elasticsearch/
-bash: cd: /var/log/elasticsearch/: Permission denied

I find that odd given I am logged in using the account I used to setup the whole thing.

That might be a problem?

Although systemctl status elasticsearch does show it running and actively listening

But maybe the account I am using and where I installed this setup.. ultimately has no rights to send data to the listener?

**Comment by mda1125** [comment]
curl localhost:9200/

Does show a typical message that shows ES is up and running

**Comment by mda1125** [comment]
ubuntu@ip-10-47-128-166:~$ systemctl status parsedmarc

● parsedmarc.service - parsedmarc watcher
   Loaded: loaded (/etc/systemd/system/parsedmarc.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-06-28 16:12:26 UTC; 5s ago
     Docs: https://domainaware.github.io/parsedmarc/
  Process: 1954 ExecStart=/usr/local/bin/parsedmarc -c /etc/parsedmarc.ini (code=exited, status=1/FAILURE)
 Main PID: 1954 (code=exited, status=1/FAILURE)

Not sure why the service is failing but if it's not actually working and running, that might explain why data isn't being sent to ES

**Comment by mda1125** [comment]
Seems like certain files can pretty much hose the service.  Once I clean out the directory.  Stop the service.  Start the service.  It's back up and running.  If I SFTP files in there, it occasionally works until I gets hung up and the service can't recover without intervention.
