### ISSUE TITLE
Org_name parsing issue

### ISSUE THREAD

**Issue by GurBal** [domainaware/parsedmarc#94]
Hi Sean,

I have been reviewing the parse DMARC data in kibana and i see some mismatches between xml and the parsed data. specifically, org_name tag. 

It looks like the utility only parses a part of the org_name from xml.

I have attached both the snippet showing difference below:

XML - 
![image](https://user-images.githubusercontent.com/51963664/60351920-03344200-9984-11e9-918f-7fe3694a0386.png)

Parsedmarc JSON 

![image](https://user-images.githubusercontent.com/51963664/60351967-1b0bc600-9984-11e9-8935-e633a42ba738.png)

Is there something i am not doing right?

**Comment by GurBal** [comment]
Also i don't see source.reverse_dns and source.base_domain in the json output.

I will try to run it in --debug mode and paste the output here.

**Comment by GurBal** [comment]
below is the snippet with --debug option 

![image](https://user-images.githubusercontent.com/51963664/60352757-c701e100-9985-11e9-801d-dada78489d1d.png)

**Comment by seanthegeek** [comment]
I haven't been able to reproduce this. Can you provide a sample aggregate report that reproduces the issue?

**Comment by GurBal** [comment]
Hi Sean,

PFA aggregate report.

[seznam.cz!cpr.ca!1561334400!1561420800.xml.zip](https://github.com/domainaware/parsedmarc/files/3350465/seznam.cz.cpr.ca.1561334400.1561420800.xml.zip)

**Comment by seanthegeek** [comment]
Fixed in parsedmarc 6.4.2. Thanks!

**Comment by GurBal** [comment]
I was wondering if you got a chance to look at why i don't see **source.reverse_dns** and **source.base_domain** in the json output?

**Comment by seanthegeek** [comment]
A black reverse DNS field indicates that there isn't a reverse DNS (PTR) record in DNS for the source IP address.

**Comment by GurBal** [comment]
I have parsed around 2K aggregate reports but it doesn't seem to be populating for any of them.

If i go manually and pick one of the source IP address in aggregate report, i am able to reverse lookup the IP but it doesn't populate in the JSON output

Snippets attached below:

![image](https://user-images.githubusercontent.com/51963664/60550633-d6668e80-9ce5-11e9-87a7-02543f3473d3.png)


![image](https://user-images.githubusercontent.com/51963664/60550646-e0888d00-9ce5-11e9-84db-a6e31b455b16.png)

**Comment by seanthegeek** [comment]
Parsedmarc uses Cloudflare's public DNS resolvers to avoid any conflicting data from internal nameservers. In that case, your network might be blocking requests to external DNS resolvers. Try configuing parsedmarc to use your local DNS resolver ipaddressesby setting them in the config file.

https://domainaware.github.io/parsedmarc/#configuration-file

**Comment by GurBal** [comment]
Working now! thanks a lot 

Also, How can i update parsedmarc to latest version from git?

**Comment by GurBal** [comment]
Working now! Thanks a lot
