### ISSUE TITLE
Make debugging output more verbose

### ISSUE THREAD

**Issue by sirio81** [domainaware/parsedmarc#95]
Hi, I was testing parsedmarc on a bunch of mails.
It takes about 10 seconds to parse them but there's a message that cause it to hang.
It doesn't crash but it takes over 10 minutes to end.
I don't have any message to debug the problem.
I had to add the messages one by one to the "report_folder" to find out witch one was causing the program to hang.
Will you add a 'debug' option to get more information about what the program is doing and when?

it may not be even possible using more processes together I guess.

Thank you.

**Comment by seanthegeek** [comment]
I just released parsedmarc 6.5, which will output each file path processed when using the `--debug` option. I also made some changes that make DNS queries faster.
