### ISSUE TITLE
Add support for reading email via Gmail API

### ISSUE THREAD

**Issue by seanthegeek** [domainaware/parsedmarc#96]
Not sure when I'll get to this

Requested by @mda1125

API docs: https://developers.google.com/gmail/api/

**Comment by seanthegeek** [comment]
Google has deprecated static passwords for Gmail. Need to prioritize adding OAuth support of Gmail and Office 365.

**Comment by edwardgoat** [comment]
@seanthegeek Im getting an IMAP timeout error whenever we process a report from a company, when using the watch flag. (the XML they send regularly exceeds 20MB daily) Hoping using the API would help for this. So +1 from me.

**Comment by mrprobz** [comment]
> Google has deprecated static passwords for Gmail. Need to prioritize adding OAuth support of Gmail and Office 365.

Hi Sean any idea when this is put on the agenda? thx
